---
settings:
  name: Astra Automation
  internal:
    pdf_enabled: true
    api_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    api_enabled: true
  rss_page: rn/whats_new.html
  versions:
  - name: Astraの自動化
    url: "/astra-automation"
    version-number: '23.01'
  - name: Astraの自動化
    url: https://docs.netapp.com/us-en/astra-automation-2208/
    version-number: '22.08'
  - name: Astraの自動化
    url: https://docs.netapp.com/us-en/astra-automation-2204/
    version-number: '22.04'
  - name: Astraの自動化
    url: https://docs.netapp.com/us-en/astra-automation-2112/
    version-number: '21.12'
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Astra Control Automation のドキュメント
    url: "/index.html"
  - section: rn
  - section: intro
  - section: get-started
  - section: rest-core
  - section: endpoints
  - section: additional
  - section: workflows_infra
  - section: workflows
  - section: python
  - section: reference
  - section: information
  - title: 以前のバージョン
    url: "/aa-earlier-versions.html"
  - title: 法的通知
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: はじめに
    links:
    - title: 概要
      url: "/intro/overview.html"
    - title: 作業を開始する前に
      url: "/get-started/before_get_started.html"
    - title: API トークンを取得します
      url: "/get-started/get_api_token.html"
    - title: 最初のAPI呼び出し
      url: "/get-started/first_call.html"
  - title: REST 実装
    links:
    - title: REST Web サービス
      url: "/rest-core/rest_web_services.html"
    - title: HTTP の詳細
      url: "/rest-core/http_details.html"
    - title: URL 形式
      url: "/rest-core/url_format.html"
  - title: その他の考慮事項については
    links:
    - title: RBAC セキュリティ
      url: "/additional/rbac.html"
    - title: コレクションを操作する
      url: "/additional/work_with_collections.html"
    - title: 診断とサポート
      url: "/additional/diagnostics_support.html"
    - title: API トークンを取り消します
      url: "/additional/revoke_token.html"
  - title: リソース
    links:
    - title: REST のリソースとコレクション
      url: "/rest-core/resources_collections.html"
    - title: Astra API リソースの要約
      url: "/endpoints/resources.html"
  - title: ワークフロー
    links:
    - title: 準備
      url: "/get-started/prepare_to_use_workflows.html"
    - title: インフラワークフロー
      url: "/workflows_infra/workflows_infra_before.html"
    - title: 管理ワークフロー
      url: "/workflows/workflows_before.html"
  - title: Python
    links:
    - title: NetApp Astra Control Python SDK
      url: "/python/astra_toolkits.html"
    - title: Python をネイティブに使用する
      url: "/python/python_before.html"
product-family:
  name: Astra
  repo: astra-family
  sidebar_label: すべてのAstraドキュメント
