---
sidebar: sidebar 
permalink: rn/about.html 
keywords: about, about this release, current release 
summary: このサイトのドキュメントでは、2つのAstra Control導入モデルに含まれるAstra Control REST APIと関連する自動化テクノロジについて説明しています。 
---
= このリリースについて
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このサイトのドキュメントでは、2つのAstra Control導入モデルに含まれるAstra Control REST APIと関連する自動化テクノロジについて説明しています。

.リリースのバージョン管理
Astra Controlのすべてのリリースには、* YY.MM *形式のバージョン番号が割り当てられます。この値は、利用可能になった年（_YY_）と月（_MM_）に基づいてバージョンを識別します。たとえば、2023年7月にAstra Control Center 23.07がリリースされました。

.ケイデンスを解放します
通常、Astra Control ServiceとAstra Control Centerの更新は同時に実行されます。しかし、これまでのAstra Control Serviceではリリースサイクルが短縮されていました。そのため、最新のAstra Control Centerリリース以降に1つ以上の差分更新が行われました。

.Astra Controlの導入
このサイトのドキュメント環境 次のAstra Controlリリース：

* Astra Controlサービス23.10
* Astra Control Center 23.10


このサイトでは両方の導入モデルのREST APIについて説明しているため、一方の導入モデルでしか使用できない機能もあります。この2つの大きな違いは、必要に応じて記録されます。

.詳細情報
最新リリースおよび以前のAstra Controlリリースの詳細については、次のページとサイトを参照してください。

* link:../rn/whats_new.html["Astra Control REST API の新機能"]
* link:../endpoints/resources.html["REST のリソースとエンドポイント"]
* https://docs.netapp.com/us-en/astra-control-center/["Astra Control Center 23.10ドキュメント"^]
* https://docs.netapp.com/us-en/astra-control-service/["Astra Control Service 23.10ドキュメント"^]
* link:../rn/earlier-versions.html["旧バージョンの Astra Automation ドキュメント"]


.ドキュメントの改善にご協力ください
Twitter *@NetAppDoc *でネットアップのドキュメントに関する通知をお送りしています。また、を作成してフィードバックを送信することもできます link:https://docs.netapp.com/us-en/contribute/["GitHub の貢献者"^] または、_doccomments@netapp.com_に電子メールを送信します。
