---
sidebar: sidebar 
permalink: rn/whats_new.html 
keywords: whats new, enhancements, new features 
summary: ネットアップでは、Astra Control REST APIを定期的に更新して、新機能、拡張機能、バグ修正を提供しています。 
---
= Astra Control REST API の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ネットアップでは、Astra Control REST APIを定期的に更新して、新機能、拡張機能、バグ修正を提供しています。



== 2022年8月10日（22.08）

このリリースでは、 REST API の拡張と更新に加え、セキュリティと管理に関する高度な機能が実装されています。



=== Astra の新しいリソース

3つの新しいリソースタイプ、* Certificate *、* Group *、* AppMirror *が追加されました。また、いくつかの既存リソースのバージョンも更新されています。



=== LDAP 認証

必要に応じて、Astra Control Centerを構成してLDAPサーバーと統合し、選択したAstraユーザーを認証することができます。を参照してください link:../workflows_infra/ldap_prepare.html["LDAP の設定"] を参照してください。



=== 拡張実行フック

実行フックのサポートは、Astra Control 21.12リリースで追加されました。既存のスナップショット前およびスナップショット後の実行フックに加えて、22.08リリースで次の種類の実行フックを構成できるようになりました。

* バックアップ前
* バックアップ後
* リストア後のPOSTコマンドです


Astra Controlでは、複数の実行フックに同じスクリプトを使用できるようになりました。



=== SnapMirrorを使用したアプリケーションのレプリケーション

NetApp SnapMirrorテクノロジを使用して、クラスタ間でデータやアプリケーションの変更をレプリケートできるようになりました。この拡張機能を使用すると、ビジネス継続性およびリカバリ機能を向上させることができます。

.関連情報
* https://docs.netapp.com/us-en/astra-control-center/release-notes/whats-new.html["Astra Control Center ：新機能"^]
* https://docs.netapp.com/us-en/astra-control-service/release-notes/whats-new.html["Astra Control Service ：新機能"^]




== 2022 年 4 月 26 日（ 2004 年 4 月 22 日）

このリリースでは、 REST API の拡張と更新に加え、セキュリティと管理に関する高度な機能が実装されています。



=== Astra の新しいリソース

2 つの新しいリソースタイプが追加されました。 * パッケージ * と * アップグレード * です。また、いくつかの既存リソースのバージョンもアップグレードされています。



=== ネームスペース単位で強化された RBAC

ロールを関連付けられたユーザにバインドする場合は、ユーザがアクセスできるネームスペースを制限できます。詳しくは、 * Role Binding API * のリファレンスおよびを参照してください link:../additional/rbac.html["RBAC セキュリティ"] を参照してください。



=== バケットの取り外し

不要になったバケットや、正常に機能していないバケットは削除できます。



=== Cloud Volumes ONTAP のサポート

Cloud Volumes ONTAP がストレージバックエンドとしてサポートされるようになりました。



=== その他の機能強化

2 つの Astra Control 製品の実装には、次のような機能強化が追加されています。

* Astra Control Center への一般的な入力
* AKS のプライベートクラスタ
* Kubernetes 1.22 のサポート
* VMware Tanzu ポートフォリオのサポート


Astra Control Center および Astra Control Service のドキュメントサイトの「新機能 * 」ページを参照してください。

.関連情報
* https://docs.netapp.com/us-en/astra-control-center/release-notes/whats-new.html["Astra Control Center ：新機能"^]
* https://docs.netapp.com/us-en/astra-control-service/release-notes/whats-new.html["Astra Control Service ：新機能"^]




== 2021 年 12 月 14 日（ 21.12 ）

このリリースでは、 REST API の拡張に加え、今後のリリース更新で Astra Control の進化をサポートするためのドキュメント構造の変更が追加されています。



=== Astra Control の各リリースに対応した、別個の Astra Automation のドキュメント

Astra Control の各リリースには、特定のリリースの機能に合わせて拡張およびカスタマイズされた独自の REST API が含まれています。Astra Control REST API の各リリースのドキュメントが、関連する GitHub コンテンツリポジトリに加え、独自の専用 Web サイトで入手できるようになりました。メインのドキュメントサイト https://docs.netapp.com/us-en/astra-automation/["Astra Control Automation の略"^] 最新リリースのドキュメントは必ず含まれています。を参照してください link:../aa-earlier-versions.html["旧バージョンの Astra Control Automation のドキュメント"] 以前のリリースについては、を参照してください。



=== REST リソースタイプの拡張

REST リソースタイプの数は、実行フックとストレージバックエンドを重視して拡張が続けられています。新しいリソースには、アカウント、実行フック、フックソース、実行フックオーバーライド、クラスタノード、 管理対象のストレージバックエンド、ネームスペース、ストレージデバイス、およびストレージノード。を参照してください link:../endpoints/resources.html["リソース"] を参照してください。



=== NetApp Astra Control Python SDK

NetApp Astra Control Python SDK は、 Astra Control 環境用の自動化コードを簡単に開発できるようにするオープンソースパッケージです。中核となるのは Astra SDK で、 REST API 呼び出しの複雑さを抽象化する一連のクラスが含まれています。また、 Python クラスをラッピングして抽象化することで、特定の管理タスクを実行するツールキットスクリプトもあります。を参照してください link:../python/astra_toolkits.html["NetApp Astra Control Python SDK"] を参照してください。



== 2021 年 8 月 5 日（ 21.08 ）

このリリースには、新しい Astra 導入モデルの導入と REST API のメジャー拡張が含まれています。



=== Astra Control Center 導入モデル

このリリースには、パブリッククラウドサービスとして提供される既存の Astra Control Service に加えて、 Astra Control Center オンプレミス導入モデルも含まれています。Astra Control Center をサイトにインストールして、ローカルの Kubernetes 環境を管理できます。2 つの Astra Control 導入モデルは同じ REST API を共有しますが、ドキュメントで必要とされるわずかな違いがあります。



=== REST リソースタイプの拡張

Astra Control REST API からアクセス可能なリソースの数が大幅に増え、多くの新しいリソースがオンプレミスの Astra Control Center の基盤となりました。新しいリソースには、 ASUP 、使用権、機能、ライセンス、設定、 サブスクリプション、バケット、クラウド、クラスタ、管理対象クラスタ、 ストレージバックエンド、およびストレージクラス。を参照してください link:../endpoints/resources.html["リソース"] を参照してください。



=== Astra 環境をサポートする追加のエンドポイント

REST リソースの拡張に加えて、 Astra Control 環境をサポートするための新しい API エンドポイントがいくつか追加されました。

OpenAPI のサポート:: OpenAPI エンドポイントは、現在の OpenAPI JSON ドキュメントおよびその他の関連リソースへのアクセスを提供します。
OpenMetrics のサポート:: OpenMetrics エンドポイントは、 OpenMetrics リソースを介してアカウントメトリックへのアクセスを提供します。




== 2021 年 4 月 15 日（ 21.04 ）

このリリースには、次の新機能と機能拡張が含まれています。



=== REST API の導入

Astra Control REST API は、 Astra Control Service と組み合わせて使用できます。REST テクノロジと現在のベストプラクティスに基づいて作成されています。この API は、 Astra 環境を自動化するための基盤となり、次の機能とメリットが含まれています。

リソース:: REST リソースには 14 種類あります。
API トークンアクセス:: REST API には、 Astra Web ユーザインターフェイスで生成できる API アクセストークンを使用してアクセスできます。API トークンを使用して、 API に安全にアクセスできます。
収集のサポート:: リソースコレクションへのアクセスに使用できる豊富なクエリパラメータセットがあります。フィルタ、ソート、ページ付けなどの処理がサポートされます。

