---
sidebar: sidebar 
permalink: workflows_infra/wf_add_cluster.html 
keywords:  
summary: クラスタを追加して、Astraで管理できるようにすることができます。 
---
= クレデンシャルを使用してクラスタを追加する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
クラスタを追加して、Astraで管理できるようにすることができます。Astra 22.11リリース以降、Astra Control CenterとAstra Control Serviceの両方でクラスタを追加できるようになりました。


NOTE: 主要なクラウドプロバイダ（AKS、EKS、GKE）のいずれかからKubernetesサービスを使用する場合、クラスタの追加は必要ありません。



== 手順1：kubeconfigファイルを取得する

Kubernetesの管理者またはサービスから* kubconfig *ファイルのコピーを取得する必要があります。



== 手順2：kubeconfigファイルを準備する

*kubeconfig *ファイルを使用する前に、次の操作を実行する必要があります。

. ファイルをYAML形式からJSON形式に変換します。
+
YAML形式のkubeconfigファイルを受信した場合は、JSONに変換する必要があります。

. base64でJSONをエンコードします。
+
base64のJSONファイルをエンコードする必要があります。



.例
次に、kubeconfigファイルをYAMLからJSONに変換し、base64でエンコードする例を示します。

`yq -o=json ~/.kube/config | base64`



== ステップ3：クラウドを選択する

ワークフローを実行 link:../workflows_infra/wf_list_clouds.html["クラウドをリストしてください"] をクリックし、クラスタを追加するクラウドを選択します。


NOTE: 選択できるクラウドは*プライベート*クラウドのみです。



== 手順4：クレデンシャルを作成する

次のREST API呼び出しを実行して、kubeconfigファイルを使用してクレデンシャルを作成します。

.HTTPメソッドとエンドポイント
このREST API呼び出しでは、次のメソッドとエンドポイントを使用します。

[cols="25,75"]
|===
| HTTP メソッド | パス 


| 投稿（ Post ） | /accounts /｛account_id｝/core/v1/credentials 
|===
.カールの例
[source, curl]
----
curl --request POST \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/core/v1/credentials" \
--include \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data  @JSONinput
----
.JSON の入力例
[source, json]
----
{
  "type" :  "application/astra-credential",
  "version" : "1.1",
  "name" : "Cloud One",
  "keyType" : "kubeconfig",
  "keyStore" : {
    "base64": encoded_kubeconfig
  },
  "valid" : "true"
}
----


== 手順5：クラスタを追加する

次のREST API呼び出しを実行してクラスタをクラウドに追加します。の値 `credentialID` 入力フィールドは、前の手順でREST API呼び出しから取得されます。

.HTTPメソッドとエンドポイント
このREST API呼び出しでは、次のメソッドとエンドポイントを使用します。

[cols="25,75"]
|===
| HTTP メソッド | パス 


| 投稿（ Post ） | /accounts /｛account_id｝/topology/v1 /雲/｛cloud_id｝/ clusters 
|===
.カールの例
[source, curl]
----
curl --request POST \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/topology/v1/clouds/<CLOUD_ID>/clusters" \
--include \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data  @JSONinput
----
.JSON の入力例
[source, json]
----
{
  "type" :  "application/astra-cluster",
  "version" : "1.1",
  "credentialID": credential_id
}
----