---
sidebar: sidebar 
permalink: workflows_infra/wf_enable_anf_dyn_pools.html 
keywords: Azure NetApp Files, ANF, dynamic ANF pools, subscription id 
summary: ANFストレージバックエンドを備えたプライベートオンプレミスクラスタで管理対象アプリケーションをバックアップする場合は、動的なANFプール機能を有効にする必要があります。これには、容量プールを拡張および縮小するときに使用するサブスクリプションIDを指定します。 
---
= 自己管理型クラスタ向けに動的ANFプールを有効化
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ANFストレージバックエンドを備えたプライベートオンプレミスクラスタで管理対象アプリケーションをバックアップする場合は、動的なANFプール機能を有効にする必要があります。これには、容量プールを拡張および縮小するときに使用するサブスクリプションIDを指定します。


NOTE: 動的ANFプールは、Azure NetApp Files（ANF）ストレージバックエンドを使用するAstraが管理するアプリケーションの機能です。これらのアプリケーションをバックアップすると、永続ボリュームが属する容量プールがAstraによって自動的に1.5倍に拡張および縮小されます。これにより、追加の恒久的な料金を支払うことなく、バックアップ用の十分なスペースが確保されます。を参照してください https://docs.netapp.com/us-en/astra-control-service/learn/azure-storage.html#application-backups["Azureアプリケーションのバックアップ"^] を参照してください。



== 手順1：AzureサブスクリプションIDを追加する

次の REST API 呼び出しを実行します。


NOTE: サブスクリプションIDやサービスプリンシパルのbase64値など、環境に応じてJSON入力例を更新する必要があります。

.HTTPメソッドとエンドポイント
このREST API呼び出しでは、次のメソッドとエンドポイントを使用します。

[cols="1,6"]
|===
| HTTP メソッド | パス 


| 投稿（ Post ） | /accounts /｛account_id｝/core/v1/credentials 
|===
.カールの例
[source, curl]
----
curl --request POST \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/core/v1/credentials" \
--include \
--header "Content-Type: application/astra-credential+json"
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data  @JSONinput
----
.JSON の入力例
[source, json]
----
{
  "keyStore": {
    "privKey": "SGkh",
    "pubKey": "UGhpcyCpcyBhbiBleGFtcGxlLg==",
    "base64": "fwogICAgJmFwcElkIjogIjY4ZmSiODFiLTY0YWYtNDdjNC04ZjUzLWE2NDdlZTUzMGZkZCIsCiAgICAiZGlzcGxheU5hbWUiOiAic3AtYXN0cmEtZGV2LXFhIiwKICAgICJuYW1lIjogImh0dHA6Ly9zcC1hc3RyYS1kZXYtcWEiLAogICAgInBhc3N3b3JkIjogIllLQThRfk9IVVJkZWZYM0pSTWJlLnpUeFBleVE0UnNwTG9DcUJjazAiLAogICAgInRlbmFudCI6ICIwMTFjZGY2Yy03NTEyLTQ3MDUtYjI0ZS03NzIxYWZkOGNhMzciLAogICAgInN1YnNjcmlwdGlvbklkIjogImIyMDAxNTVmLTAwMWEtNDNiZS04N2JlLTNlZGRlODNhY2VmNCIKfQ=="
  },
  "name": "myCert",
  "type": "application/astra-credential",
  "version": "1.1",
  "metadata": {
    "labels": [
      {
        "name": "astra.netapp.io/labels/read-only/credType",
        "value": "service-account"
      },
      {
        "name": "astra.netapp.io/labels/read-only/cloudName",
        "value": "OCP"
      },
      {
        "name": "astra.netapp.io/labels/read-only/azure/subscriptionID",
        "value": "b212156f-001a-43be-87be-3edde83acef5"
      }
    ]
  }
}
----


== 手順2：必要に応じてバケットを追加する

必要に応じて、管理対象アプリケーションにバケットを追加する必要があります。



== ステップ3：管理対象アプリのバックアップを作成する

ワークフローを実行 link:../workflows/wf_create_backup.html["アプリケーションのバックアップを作成する"]。元の永続ボリュームが存在する容量プールは、自動的に拡張および縮小されます。



== 手順4：イベントログを確認する

アクティビティイベントはバックアップ中に記録されます。ワークフローを実行 link:../workflows/wf_list_notifications.html["通知を一覧表示します"] をクリックしてメッセージを表示します。
