---
sidebar: sidebar 
permalink: workflows_infra/workflows_infra_before.html 
keywords: workflows, infrastructure workflows, preparation 
summary: これらのワークフローを使用して、Astra Control Centerの導入で使用するインフラストラクチャを作成および管理できます。多くの場合、このワークフローはAstra Control Serviceでも使用できます。 
---
= インフラワークフローを使用するための準備
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
これらのワークフローを使用して、Astra Control Centerの導入で使用するインフラストラクチャを作成および管理できます。多くの場合、このワークフローはAstra Control Serviceでも使用できます。


NOTE: これらのワークフローは、ネットアップがいつでも拡張および強化できるため、定期的に確認する必要があります。



== 一般的な準備

いずれかの Astra ワークフローを使用する前に、を確認してください link:../get-started/prepare_to_use_workflows.html["ワークフローを使用する準備をします"]。



== ワークフローのカテゴリ

インフラのワークフローは、さまざまなカテゴリに分類されているため、必要なワークフローを簡単に見つけることができます。

[cols="25,75"]
|===
| カテゴリ | 説明 


| ID とアクセス | これらのワークフローを使用すると、 Astra のアイデンティティとアクセス方法を管理できます。リソースには、ユーザ、クレデンシャル、トークンが含まれます。 


| LDAP の設定 | 必要に応じて、選択したユーザーの認証にLDAPを使用するようにAstra Control Centerを設定できます。 


| クラスタ | 管理対象の Kubernetes クラスタを追加すると、クラスタに含まれるアプリケーションを保護およびサポートできるようになります。 


| クラウド | これらのワークフローは、Astra Control REST APIを使用して利用できるクラウドへのアクセスを提供します。 


| バケット | これらのワークフローを使用して、バックアップの格納に使用する S3 バケットを作成および管理できます。 


| ストレージ | これらのワークフローを使用して、ストレージバックエンドとストレージボリュームを追加および管理できます。 
|===