---
sidebar: sidebar 
permalink: intro/introduction.html 
keywords: introduction, Astra REST API 
summary:  
---
= Astra REST API の概要
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Astra サービスは、 Curl などのプログラミング言語やユーティリティを使用して直接アクセスできる REST API を提供します。API の主な特長とメリットを以下に示します。


NOTE: REST API にアクセスするには、最初に Astra Web ユーザインターフェイスにサインインして、 API トークンを生成する必要があります。トークンは各 API 要求に含める必要があります。



==== REST テクノロジを基盤として構築

REST テクノロジを使用して Astra API が作成され、最新のベストプラクティスが適用されている。中核となるテクノロジは、 HTTP 、 JSON 、 RBAC です。



==== REST エンドポイントリソースとオブジェクトモデルの間のマッピングをクリアします

リソースへのアクセスに使用される外部の REST エンドポイントは、 Astra サービスによって内部的に管理されている整合性のあるオブジェクトモデルにマッピングされます。オブジェクトモデルは、エンティティと関係（ ER ）のモデリングを使用して設計され、 API のアクションと応答を明確に定義できます。



==== 豊富なクエリパラメータ

REST API には、リソースコレクションへのアクセスに使用できる豊富なクエリパラメータが用意されています。フィルタ、ソート、ページ付けなどの処理がサポートされます。



==== Astra Web UI とのアライメント

設計された Astra Web ユーザインターフェイスは REST API に対応しているため、 2 つのアクセスパスとユーザエクスペリエンスの間で一貫性があります。



==== 堅牢なデバッグおよび問題の特定データ

Astra REST API は、内部で生成されたイベントや通知など、堅牢なデバッグ機能と問題の特定機能を提供します。



==== 高度なオートメーション技術の基盤

REST API に直接アクセスするだけでなく、 REST API をベースとするその他の自動化テクノロジも使用できます。
