---
sidebar: sidebar 
permalink: rest-core/resources_collections.html 
keywords: concepts 
summary:  
---
= リソースとコレクション
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Astra Control REST API を使用すると、リソースインスタンスとリソースインスタンスのコレクションにアクセスできます。


NOTE: 概念的には REST * リソース * は、オブジェクト指向プログラミング（ OOP ）言語およびシステムで定義される * オブジェクト * に似ています。これらの用語が同じ意味で使用されることもあります。ただし一般には、外部 REST API のコンテキストで使用する場合は「リソース」が推奨され、サーバに格納される対応するステートフルインスタンスデータには「オブジェクト」が使用されます。



== Astra リソースの属性

Astra Control REST API は、 RESTful 設計の原則に準拠しています。各アストラリソースインスタンスは、明確に定義されたリソースタイプに基づいて作成されます。同じタイプのリソースインスタンスのセットを * 集合 * と呼びます。API 呼び出しは、個々のリソースまたはリソースの集合に対して機能します。



===== リソースタイプ

Astra Control REST API に含まれるリソースタイプには、次の特徴があります。

* すべてのリソースタイプはスキーマを使用して定義されます（通常は JSON 形式）。
* すべてのリソーススキーマには、リソースタイプとバージョンが含まれています
* リソースタイプはグローバルに一意です




===== リソースインスタンス

Astra Control REST API から使用できるリソースインスタンスには、次のような特徴があります。

* リソースインスタンスは、単一のリソースタイプに基づいて作成されます
* リソースタイプは、 ［ メディアタイプ ］ の値を使用して示されます
* インスタンスは、アストラサービスによって管理されるステートフルデータで構成されます
* 各インスタンスには、一意で長く存続する URL を使用してアクセスできます
* リソースインスタンスが複数のリプレゼンテーションを持つことができる場合は、異なるメディアタイプを使用して必要なリプレゼンテーションを要求できます




===== リソースコレクション

Astra Control REST API で使用できるリソース収集には、次のような特徴があります。

* 単一のリソースタイプの一連のリソースインスタンスをコレクションと呼びます
* 一連のリソースには、一意で一時的な URL があります




===== インスタンス ID

すべてのリソースインスタンスには、作成時に識別子が割り当てられます。この識別子は 128 ビットの UUIDv4 値です。割り当てられた UUIDv4 の値は、グローバルに一意で変更できません。新しいインスタンスを作成する API 呼び出しを発行すると、関連付けられた ID を持つ URL が HTTP 応答の「 Location 」ヘッダーで呼び出し元に返されます。リソースインスタンスを以降の呼び出しで参照する際には、この識別子を抽出して使用できます。


NOTE: リソース識別子は、コレクションで使用される主キーです。



== Astra のリソースに共通の構造

すべてのアストラ制御リソースは、共通の構造を使用して定義されます。



===== 共通のデータ

すべてのアストラリソースには、次の表に示すキーと値が含まれています。

[cols="15,85"]
|===
| キーを押します | 説明 


| を入力します | グローバルに一意なリソースタイプ。 * リソースタイプ * と呼ばれます。 


| バージョン | * リソースバージョン * と呼ばれるバージョン識別子。 


| ID | グローバル一意識別子。 * リソース識別子 * と呼ばれます。 


| メタデータ | ユーザラベルやシステムラベルなどのさまざまな情報を含む JSON オブジェクト。 
|===


===== メタデータオブジェクト

各アストラリソースに含まれるメタデータ JSON オブジェクトには、次の表に示すキーと値が含まれています。

[cols="15,85"]
|===
| キーを押します | 説明 


| ラベル | リソースに関連付けられているクライアント指定のラベルの JSON 配列。 


| 作成タイムスタンプ | リソースが作成されたときのタイムスタンプを含む JSON 文字列。 


| modificationTimestamp | リソースの最終変更日時を示す ISO-8601 形式のタイムスタンプを含む JSON 文字列。 


| 作成者 | リソースを作成したユーザ ID の UUIDv4 識別子を含む JSON 文字列。リソースが内部システムコンポーネントによって作成され、作成するエンティティに関連付けられている UUID がない場合は、「 * null * UUID 」が使用されます。 
|===


===== リソースの状態

選択されたリソースは ' ライフサイクルの移行とアクセス制御のオーケストレーションに使用される価値を示します
