---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-notifications-.html 
summary: 通知を取得する 
---
= 通知を取得する
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/notifications/{notification_id}`#

JSONレスポンスボディに格納された通知APIリソースを返します。



== パラメータ

[cols="5*"]
|===
| Name | を入力します | 入力 | 必須 | 説明 


| account_id | string | path（パス） | True  a| 
包含するアカウントリソースのID

* 例：{{.Account}}




| notification_id | string | path（パス） | True  a| 
一覧表示する通知コレクションのID

|===


== 応答

[source]
----
Status: 200, Returns the stored Notification API resource in the JSON response body.
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 
リソースのメディアタイプ。定義された値は次のとおりです：

* "application/astra-notification"




| バージョン | string | True  a| 
リソースのバージョン。定義された値は次のとおりです：

* "1.0"
* "1.1"
* "1.2"
* "1.3"




| ID | string | True  a| 
リソースのグローバル一意識別子。定義された値は次のとおりです：

* UUIDv4スキーマに準拠




| 名前 | string | True  a| 
イベントのドット表記（.）階層名を含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：3
* 最大長さ：127
* 定義された正規表現は次のとおりです："^(([a-z])_(\.))_([a-z])+$"




| sequenceCount | 番号 | True  a| 
シーケンスカウントを含むJSON数値。この数値は、新しいイベントが受信されるたびにシステムによって増分されます。



| まとめ | string | True  a| 
イベントの短縮形（40文字未満）の要約を含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：3
* 最大長さ：79




| eventTime | string | True  a| 
イベントが発生した日時を示すタイムスタンプを含むJSON文字列。定義値は次のとおりです：

* ISO-8601 Date Time Schemaに準拠




| ソース | string | True  a| 
イベントを生成するサービスの小文字の名前を含むJSON文字列。定義値は次のとおりです：

* 最小長さ：1
* 最大長さ：19
* 定義された正規表現は次のとおりです："^([a-z-])*$"




| resourceID | string | True  a| 
イベントに関連付けられたリソース ID を含む JSON 文字列。定義された値は次のとおりです：

* Astra識別子スキーマに準拠




| additionalResourceIDs | array[string] | True  a| 
JSON文字列のJSON配列。各文字列には、イベントに関連付けられた追加リソースのリソースIDが含まれています。「resourceID」フィールドにはこのイベントに関連付けられた主要なリソースが含まれていますが、このフィールドには同じイベントに関連付けられる追加のリソースIDをいくつでも含めることができます。イベントに関連付けられた追加リソースがない場合、配列は空になります。定義された値は次のとおりです：

* Astra識別子スキーマに準拠




| resourceType | string | True  a| 
イベントに関連付けられたリソースのメディアタイプを含むJSON文字列。定義値は次のとおりです：

* 最小長さ：4
* 最大長さ：79
* 定義された正規表現は次のとおりです："^application\/astra-([a-zA-Z])+$"




| correlationID | string | True  a| 
関連するイベントをグループ化できるようにするUUIDv4相関IDを含むJSON文字列。定義値は次のとおりです：

* Astra識別子スキーマに準拠




| severity | string | True  a| 
イベントの深刻度を示す以下のいずれかの値を含むJSON文字列。定義値は次のとおりです：

* 「クリア済み」 - 以前に報告された、ある状態を説明する事象がもはやアクティブではないことを示します。重大度が「クリア済み」のイベントは、同じサマリーと相関IDを使用して照合できるようにします。
* 「不確定」 - 重大度を判断できないことを示します。
* 「informational」 - 予期される正常な状態変化を示します（X.733では定義されていません）。
* 「警告」 - 重大な影響が現れる前に、潜在的または差し迫ったサービス障害を検出したことを示します。
* 「critical」 - サービスに影響を与える状態が発生し、直ちに是正措置が必要であることを示します。「cleared」、「indeterminate」、「warning」、「critical」の定義は、CCITT X.733の8.1.2.3項の定義に基づいています。




| class | string | True  a| 
イベントのクラスを示す以下のいずれかの値を含むJSON文字列。定義値は次のとおりです：

* 「system」 - このイベントは、内部イベントまたはリクエストに関連しています。
* 「user」 - このイベントは、ユーザーが開始したイベントまたはリクエストに関連しています。
* 「セキュリティ」 - このイベントはセキュリティ上の問題に関連しています。




| description | string | True  a| 
イベントに関する詳細な説明文を含むJSON文字列。定義されている値は次のとおりです：

* 最小長さ：3
* 最大長さ：1023




| descriptionURL | string | False  a| 
バナー内のボタンを有効化し、外部ドキュメントにリンクするURLを含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：3
* 最大長さ：4095




| correctiveAction | string | False  a| 
当該事象に対応して取るべき是正措置に関する詳細な説明文を含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：3
* 最大長さ：1023




| correctiveActionURL | string | False  a| 
バナー内のボタンをUI内のページにリンクするURLを含むJSON文字列。このURLによって問題が解決されます。定義値は次のとおりです：

* 最小長さ：3
* 最大長さ：4095




| 可視性 | array[string] | False  a| 
JSON文字列の配列で、各文字列はイベントの表示が許可されているRBACロールを示します。ロールはOR定義されます。オプション。省略した場合、任意のRBACロールを持つユーザーがイベントを表示できます。定義された値は次のとおりです：

* 最小長さ：1
* 最大長さ：63




| デスティネーション | array[string] | False  a| 
JSON文字列のJSON配列。各文字列は、イベントの追加宛先を示します。これらにより、サービスはActivityサービスの活動ログに加えて、イベントをどこにルーティングする必要があるかについてのヒントを提供できるようになります。任意。定義された値は次のとおりです：

* 「notification」 - このイベントは通知としてマークされ、通知APIエンドポイントを通じてアクセスできるようになります。
* 「banner」 - このイベントはバナーとしてマークされています。
* 「サポート」 - このイベントはサポート関連のイベントとしてマークされています。




| resourceURI | string | False  a| 
イベントに関連付けられた URI を含む JSON 文字列。API 操作に関連するイベントのみが含まれます。定義値は次のとおりです：

* 最小長さ：3
* 最大長さ：4095




| resourceCollectionURL | array[string] | False  a| 
JSON文字列のJSON配列。各文字列は、イベントに関連付けられたリソースの完全に展開されたアクセスURLを示します。定義された値は次のとおりです：

* 最小長さ：1
* 最大長さ：1023




| resourceMethod | string | False  a| 
呼び出されたHTTPメソッドを含むJSON文字列。API操作に関連するイベントのみに含まれます。定義された値は次のとおりです：

* 「options」 - OPTIONS API操作
* 「post」 - POST API操作
* 「get」 - GET API操作
* 「put」 - PUT API操作
* 「delete」 - DELETE API操作




| resourceMethodResult | string | False  a| 
呼び出されたHTTPメソッドの結果を含むJSON文字列。API操作に関連するイベントのみに含まれます。定義値は次のとおりです：

* 定義された正規表現は次のとおりです："^[1-5][0-9]{2}$"




| ユーザーID | string | False  a| 
イベントに関連付けられたユーザーIDを含むJSON文字列。ユーザーが開始した操作に関連するイベントのみが含まれます。定義値は次のとおりです：

* Astra識別子スキーマに準拠




| accountID | string | False  a| 
イベントに関連付けられたアカウントIDを含むJSON文字列。アカウントに関連付けられたイベントのみが含まれます。定義値は次のとおりです：

* Astra識別子スキーマに準拠




| data | link:#data["data"] | False  a| 
イベント固有の追加情報を含むJSONオブジェクト。



| メタデータ | link:#type_astra_metadata["type_astra_metadata"] | True  a| 
リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astraメタデータスキーマに準拠


|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-notification",
  "version": "1.3",
  "id": "03c645d6-75f0-59b0-95f2-862ae344ea27",
  "name": "astra.app.discovery.failed",
  "sequenceCount": 48923,
  "summary": "Application Discovery Failed",
  "eventTime": "2020-08-06T12:24:51.846543Z",
  "source": "composite-compute",
  "resourceID": "f670bf11-8850-44bd-b330-815af6186a06",
  "additionalResourceIDs": [
    "84dfee99-b7b2-46d2-9021-0a1a9a5df1d6",
    "abb32003-07b9-49b1-9938-1cf6d2f33566"
  ],
  "resourceType": "application/astra-app",
  "correlationID": "3c603442-cfca-4af9-9f1b-40dde5c7a806",
  "severity": "warning",
  "class": "user",
  "description": "Discovering the application 'mysql' was unsuccessful. K8s error 442. Application marked in state 'error'.",
  "destinations": [
    "notification"
  ],
  "resourceURI": "/accounts/fdaa655c-15ab-4d34-aa61-1e9098e67be0/topology/v1/managedClusters/dfd9de2d-6f0b-437b-a737-c8f7f176cd14/apps/f670bf11-8850-44bd-b330-815af6186a06",
  "resourceCollectionURL": [
    "https://www.astra.io/accounts/fdaa655c-15ab-4d34-aa61-1e9098e67be0/topology/v1/clouds/0df3f1a0-7203-4c12-aabf-a7bee6302671/clusters/dfd9de2d-6f0b-437b-a737-c8f7f176cd14/namespaces/f8b58091-4b9c-4c64-9b40-018dbaf7c5de/apps/f670bf11-8850-44bd-b330-815af6186a06",
    "https://www.astra.io/accounts/fdaa655c-15ab-4d34-aa61-1e9098e67be0/topology/v1/clouds/0df3f1a0-7203-4c12-aabf-a7bee6302671/clusters/dfd9de2d-6f0b-437b-a737-c8f7f176cd14/namespaces/923708f8-0435-45b5-8c00-fbdef3ffaf25/apps/f670bf11-8850-44bd-b330-815af6186a06"
  ],
  "userID": "abda967f-cd2c-4237-908e-99266648c553",
  "accountID": "f126d214-bccf-4558-86b4-2137a41e734f",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 応答

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 応答

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 



| invalidParams | 配列[link:#invalidParams["invalidParams"]] | False  a| 
無効なクエリパラメータのリスト

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 応答

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== エラー

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.エラー応答の例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 用語の意味

.定義を参照
[%collapsible]
====
[role="api-collapsible-fifth-title"]
data

イベント固有の追加情報を含むJSONオブジェクト。

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| ttl | 番号 | False  a| 
eventTimeからの秒数を示すJSON数値で、イベントが保持される期間を表します。このフィールドは、イベントが指定された秒数後に自動的に削除される場合にのみ含まれます。削除された場合、イベントに通知先が設定されていると、関連するすべての通知も削除されます。削除された場合、イベントにバナーの掲載先が設定されていると、そのバナーも削除されます。このフィールドが存在しない場合（または値が「0」の場合）は、イベントは自動的に削除されません。



| isAcknowledgeable | string | False  a| 
バナーを非表示にできるかどうかを示すJSON文字列。定義値は次のとおりです：

* 「true」 - バナーは非表示にできます
* 「false」 - バナーは非表示にできません


|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 



| Value | string | True  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata

リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astraメタデータスキーマに準拠


[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| ラベル | 配列[link:#type_astra_label["type_astra_label"]] | True  a| 



| 作成タイムスタンプ | string | True  a| 



| modificationTimestamp | string | True  a| 



| 作成者 | string | True  a| 



| modifiedBy | string | False  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 
無効なクエリパラメータの名前



| 理由 | string | True  a| 
クエリパラメータが無効な理由

|===
====