---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-k8s-v1-appmirrors.html 
summary: すべてのAppMirrorリソースを表示 
---
= すべてのAppMirrorリソースを表示
:allow-uri-read: 
:imagesdir: ../media/


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/appMirrors`#

コレクション内の一致するすべてのリソースのJSON配列を返します。リクエストで個別のフィールドが指定されている場合、アイテムのJSON配列には、一致する各リソースに対して要求されたフィールドが、指定された順序で含まれます。



[[parameters]]
== パラメータ

[cols="5*"]
|===
| Name | を入力します | 入力 | 必須 | 説明 


| account_id | string | path（パス） | True  a| 
包含するアカウントリソースのID

* 例：{{.Account}}




| 含める | string | query | False  a| 
コレクションを一覧表示する際に、どのフィールドを返すかを指定します。

URLの例："include=id"、"include=id,name"

OpenAPI の例："id"



| 制限（ Limit ） | string | query | False  a| 
コレクションを一覧表示する際に返されるリソースの最大数を示します。

URLの例："limit=2"

OpenAPI の例："2"



| フィルタ | string | query | False  a| 
コレクションを一覧表示する際に、リソースを返すためにどのフィールドを一致させる必要があるかを示します。

サポートされているオペレータは次のとおりです：

* eq - 等号
* lt/gt - より小さい/より大きい
* lte/gte - 以下/以上


URLの例："filter=field%20eq%20%27value%27"

OpenAPI の例：「field eq 'value'」

|===


[[response]]
== 応答

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 項目 | 配列[いずれか：link:#appMirror_1_1_get_response_body["appMirror_1.1_get_response_body"]、配列[]] | True  a| 



| メタデータ | link:#type_astra_metadata_list["type_astra_metadata_list"] | True  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-appMirrors",
  "version": "1.1",
  "items": [
    {
      "type": "application/astra-appMirror",
      "version": "1.1",
      "id": "f1c98c2e-6391-42d3-8b21-3e75dac048a3",
      "sourceAppID": "efd639b6-fc92-4112-8841-0c0ab7890ae0",
      "sourceClusterID": "5789e026-c2e2-41e9-ab00-9766bcfa8951",
      "destinationAppID": "cd7b6d91-fc19-4983-a754-9a7bb4d80a7b",
      "destinationClusterID": "c5d023a9-4061-4a8a-bfbf-3be11ff06226",
      "namespaceMapping": [
        {
          "clusterID": "5789e026-c2e2-41e9-ab00-9766bcfa8951",
          "namespaces": [
            "ns1-src",
            "ns2-src"
          ]
        },
        {
          "clusterID": "c5d023a9-4061-4a8a-bfbf-3be11ff06226",
          "namespaces": [
            "ns1-dest",
            "ns2-dest"
          ]
        }
      ],
      "state": "established",
      "stateTransitions": [
        {
          "from": "establishing",
          "to": [
            "established",
            "deleting"
          ]
        },
        {
          "from": "established",
          "to": [
            "failingOver",
            "deleting"
          ]
        },
        {
          "from": "failingOver",
          "to": [
            "failedOver",
            "deleting"
          ]
        },
        {
          "from": "failedOver",
          "to": [
            "establishing",
            "deleting"
          ]
        },
        {
          "from": "deleting",
          "to": [
            "deleted"
          ]
        }
      ],
      "stateDesired": "established",
      "stateAllowed": [
        "failedOver",
        "deleted"
      ],
      "stateDetails": [
        {
          "type": "https://astra.netapp.io/stateDetails/1",
          "title": "AppMirror relationship established",
          "detail": "The AppMirror relationship has been successfully established."
        }
      ],
      "healthState": "normal",
      "healthStateTransitions": [
        {
          "from": "indeterminate",
          "to": [
            "normal",
            "warning",
            "critical"
          ]
        },
        {
          "from": "normal",
          "to": [
            "indeterminate",
            "warning",
            "critical"
          ]
        },
        {
          "from": "warning",
          "to": [
            "indeterminate",
            "normal",
            "critical"
          ]
        },
        {
          "from": "critical",
          "to": [
            "indeterminate",
            "normal",
            "warning"
          ]
        }
      ],
      "healthStateDetails": [
        {
          "type": "https://astra.netapp.io/stateDetails/2",
          "title": "SnapMirror syncing successfully",
          "detail": "All SnapMirror relationships are synchronizing as expected."
        }
      ],
      "metadata": {
        "labels": [],
        "creationTimestamp": "2020-08-06T12:24:52.256624Z",
        "modificationTimestamp": "2020-08-06T12:24:52.256624Z",
        "createdBy": "11c0cfa1-4f27-4ef7-a21c-cb452fc5c9aa"
      }
    },
    {
      "type": "application/astra-appMirror",
      "version": "1.1",
      "id": "114633f0-5b59-4bd7-adce-a9ba4423a1bd",
      "sourceAppID": "eaf8b854-211d-460a-ac18-d093d8e2ac70",
      "sourceClusterID": "fcb27b51-ebb7-40ca-b8f1-1d23ebd06889",
      "destinationAppID": "e829c5e0-750f-44ad-a684-aee85be2c2bb",
      "destinationClusterID": "fcb27b51-ebb7-40ca-b8f1-1d23ebd06889",
      "namespaceMapping": [
        {
          "clusterID": "fcb27b51-ebb7-40ca-b8f1-1d23ebd06889",
          "namespaces": [
            "app-namespace"
          ],
          "role": "source"
        },
        {
          "clusterID": "fcb27b51-ebb7-40ca-b8f1-1d23ebd06889",
          "namespaces": [
            "destination-app-namespace"
          ],
          "role": "destination"
        }
      ],
      "storageClasses": [
        {
          "storageClassName": "destination-sc",
          "clusterID": "fcb27b51-ebb7-40ca-b8f1-1d23ebd06889",
          "role": "destination"
        }
      ],
      "state": "established",
      "stateTransitions": [
        {
          "from": "establishing",
          "to": [
            "established",
            "deleting"
          ]
        },
        {
          "from": "established",
          "to": [
            "failingOver",
            "deleting"
          ]
        },
        {
          "from": "failingOver",
          "to": [
            "failedOver",
            "deleting"
          ]
        },
        {
          "from": "failedOver",
          "to": [
            "establishing",
            "deleting"
          ]
        }
      ],
      "stateDesired": "established",
      "stateAllowed": [
        "failedOver",
        "deleted"
      ],
      "stateDetails": [],
      "transferState": "idle",
      "transferStateTransitions": [
        {
          "from": "transferring",
          "to": [
            "idle"
          ]
        },
        {
          "from": "idle",
          "to": [
            "transferring"
          ]
        }
      ],
      "transferStateDetails": [
        {
          "type": "https://astra.netapp.io/stateDetails/24",
          "title": "Snapshot replication completed",
          "detail": "A snapshot was replicated to the destination.",
          "additionalDetails": {
            "completionTime": "2023-07-06T22:46:39Z",
            "snapshotID": "ae60820d-e963-4eab-8bb3-9159e9f012f0",
            "startTime": "2023-07-06T22:46:08Z"
          }
        }
      ],
      "healthState": "normal",
      "healthStateTransitions": [],
      "healthStateDetails": [
        {
          "type": "https://astra.netapp.io/stateDetails/24",
          "title": "Snapshot replication completed",
          "detail": "A snapshot was replicated to the destination.",
          "additionalDetails": {
            "completionTime": "2023-07-06T22:46:39Z",
            "snapshotID": "ae60820d-e963-4eab-8bb3-9159e9f012f0",
            "startTime": "2023-07-06T22:46:08Z"
          }
        }
      ],
      "metadata": {
        "labels": [],
        "creationTimestamp": "2023-07-06T22:45:24Z",
        "modificationTimestamp": "2023-07-06T22:45:24Z",
        "createdBy": "cc420827-f968-4da7-9e72-df8a0fd52f94"
      }
    }
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


[[response]]
== 応答

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


[[response]]
== 応答

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 



| invalidParams | 配列[link:#invalidParams["invalidParams"]] | False  a| 
無効なクエリパラメータのリスト

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


[[response]]
== 応答

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


[[error]]
== エラー

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.エラー応答の例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


[[definitions]]
== 用語の意味

.定義を参照
[%collapsible]
====
[[namespaceMapping]]
[role="api-collapsible-fifth-title"]
namespaceMapping

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| clusterID | string | False  a| 
名前空間が指定されているクラスタの識別子。定義されている値は次のとおりです：

* Astra識別子スキーマに準拠




| ネームスペース | array[string] | False  a| 
クラスタで使用するネームスペースのリスト。インデックスによって他のクラスタのネームスペースリストと関連付けられます。定義されている値は次のとおりです：

* 最小長さ：1
* 最大長さ：63
* DNS 1123 Label Schemaに準拠




| ロール | string | False  a| 
この名前空間定義の初期の役割。このパラメータは、同一クラスタ内レプリケーション構成を使用する場合を除き、オプションです。定義値は次のとおりです：

* "ソース"
* "デスティネーション"


|===
[[storageClasses]]
[role="api-collapsible-fifth-title"]
storageClasses

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| clusterID | string | False  a| 
ストレージクラスが指定されているクラスタの識別子。定義されている値は次のとおりです：

* Astra識別子スキーマに準拠




| storageClassName | string | False  a| 
「clusterID」で指定されたクラスタ上でPVCを作成する際に使用するストレージクラスの名前。定義値は次のとおりです：

* 最小長さ：1
* 最大長さ：255




| ロール | string | False  a| 
このストレージクラス定義の初期ロール。このパラメータは、同一クラスタレプリケーション構成を使用する場合を除き、オプションです。定義値は次のとおりです：

* "ソース"
* "デスティネーション"


|===
[[type_astra_stateTransition]]
[role="api-collapsible-fifth-title"]
type_astra_stateTransition

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| - | string | True  a| 



| - | array[string] | True  a| 

|===
[[additionalDetails]]
[role="api-collapsible-fifth-title"]
additionalDetails

[[type_astra_stateDetail]]
[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | False  a| 

|===
[[type_astra_label]]
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 



| Value | string | True  a| 

|===
[[type_astra_metadata_update]]
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。作成時に指定しない場合、ラベルのないメタデータオブジェクトが作成されます。更新時に指定されていない場合、メタデータオブジェクトのラベル、creationTimestamp および createdBy は、変更なしで保持されます。


[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| ラベル | 配列[link:#type_astra_label["type_astra_label"]] | False  a| 



| 作成タイムスタンプ | string | False  a| 



| modificationTimestamp | string | False  a| 



| 作成者 | string | False  a| 



| modifiedBy | string | False  a| 

|===
[[appMirror_1_1_get_response_body]]
[role="api-collapsible-fifth-title"]
appMirror_1.1_get_response_body

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 
リソースのメディアタイプ。定義された値は次のとおりです：

* 「application/astra-appMirror」




| バージョン | string | True  a| 
リソースのバージョン。定義された値は次のとおりです：

* "1.0"
* "1.1"




| ID | string | True  a| 
リソースのグローバル一意識別子。定義された値は次のとおりです：

* UUIDv4スキーマに準拠




| sourceAppID | string | True  a| 
ソースアプリケーションの識別子。sourceAppIDとdestinationAppIDを入れ替えた場合にのみ更新されます。定義値は次のとおりです：

* Astra識別子スキーマに準拠




| sourceClusterID | string | True  a| 
ソースアプリケーションをホストしている管理対象クラスタの識別子。このフィールドは読み取り専用であり、ソースアプリケーションのホストクラスタに基づいて決定されます。アップデートで提供される場合、ソースアプリケーションのクラスタIDと一致する必要があるため、sourceAppIDとdestinationAppIDを入れ替える場合にのみ変更できます。定義された値は次のとおりです：

* Astra識別子スキーマに準拠




| destinationAppID | string | False  a| 
デスティネーション アプリケーションの識別子。作成時に指定することはできません。なぜなら、関係の初期化の一環として新しいアプリIDが生成されるからです。sourceAppIDとdestinationAppIDを入れ替えた場合にのみ更新可能です。定義値は次のとおりです：

* Astra識別子スキーマに準拠




| デスティネーション クラスタ ID | string | True  a| 
デスティネーション アプリケーションをホストする管理対象クラスタの識別子。作成時に必ず指定する必要があります。これは、デスティネーション アプリケーションが作成されるクラスタを決定するためです。更新時に指定される場合、デスティネーション アプリケーションのクラスタIDと一致する必要があるため、sourceAppIDとdestinationAppIDを入れ替える場合にのみ変更できます。定義された値は次のとおりです：

* Astra識別子スキーマに準拠




| namespaceMapping | 配列[link:#namespaceMapping["namespaceMapping"]] | False  a| 
宛先アプリケーションを作成する際に使用する名前空間（または複数の名前空間）。これは、ソースアプリケーションの名前空間に対応します。各 JSON オブジェクトには「clusterID」と「namespaces」というフィールドが含まれており、「clusterID」の値はソースまたはデスティネーション クラスタの JSON 文字列 ID で、「namespaces」の値は JSON 文字列の JSON 配列です。各クラスタには必ず 1 つの JSON オブジェクトが存在し、名前空間はインデックスによって関連付けられます。指定しない場合は、ソース クラスタの同じ名前空間がデスティネーション クラスタで使用されます。定義された値は次のとおりです：

* 最小長さ：0
* 最大長さ：2




| storageClasses | 配列[link:#storageClasses["storageClasses"]] | False  a| 
新しい永続ボリューム要求（PVC）を作成するときにデスティネーション クラスタで使用されるストレージクラス。各JSONオブジェクトには「clusterID」と「storageClassName」のフィールドが含まれており、「clusterID」の値はソースまたはデスティネーション クラスタのJSON文字列IDで、「storageClassName」はそのクラスタでPVCを作成する際に使用するストレージクラスです。指定されていない場合、またはクラスタに対して値が欠落している場合は、そのクラスタにはデフォルトのストレージクラスが使用されます。定義された値は次のとおりです：

* 最小長さ：0
* 最大長さ：2




| 状態 | string | True  a| 
関係の状態。定義値は次のとおりです：

* 「establishing」 - 関係が構築されつつある。
* 「established」 - 関係が作成されます。
* 「failingOver」- アプリケーションのデスティネーション クラスタへのフェイルオーバーが進行中です。
* 「failedOver」- アプリケーションのデスティネーション クラスタへのフェイルオーバーが完了しました。
* 「削除中」 - 関係によって作成されたリソースがクリーンアップされています。
* 「削除済み」 - 関係が整理され、削除されました。




| stateTransitions | 配列[link:#type_astra_stateTransition["type_astra_stateTransition"]] | False  a| 
許可された状態遷移。このリソースでは、以下の状態遷移が可能です：

* 「establishing」：「established」、「deleting」
* "established"："failingOver"、"deleting"
* "failingOver"："failedOver"、"deleting"
* "failedOver"："establishing"、"deleting"
* "deleting"："deleted"
* 「削除済み」：




| stateDesired | string | True  a| 
関係の望ましい状態。作成時に有効な値は「established」のみです。定義値は次のとおりです：

* 「established」 - 関係が作成されます。
* 「failedOver」- アプリケーションのデスティネーション クラスタへのフェイルオーバーが完了しました。
* 「削除済み」 - 関係性は正常にクリーンアップされ、削除されました。




| stateAllowed | array[string] | False  a| 
特定の状態で要求できる状態。各定義済み状態において、以下の状態を要求することができます。

* 「establishing」：「established」、「deleted」
* "established"："failedOver"、"deleted"
* "failingOver"："failedOver"、"deleted"
* "failedOver": "established"、"deleted"
* "deleting"："deleted"
* "deleted"："削除済み"




| stateDetails | 配列[link:#type_astra_stateDetail["type_astra_stateDetail"]] | True  a| 
現在の状態に関する追加の詳細情報（現在の状態に至った理由を含む）。詳細情報がない場合は、この配列は空になります。定義された値は次のとおりです：

* 最小アイテム数：0




| transferState | string | False  a| 
現在または直近のスナップショット転送の状態。定義値は次のとおりです：

* 「転送中」 - 新しいスナップショットが作成され、現在デスティネーション クラスタにレプリケートされています。この状態には、以前の試行で失敗し、継続的に再試行されている転送も含まれます。
* 「idle」 - 現在、転送処理は行われていません。




| transferStateTransitions | 配列[link:#type_astra_stateTransition["type_astra_stateTransition"]] | False  a| 
特定の定義済み状態からの許可された状態遷移。このリソースでは、以下の状態遷移が可能です：

* "transferring": "idle"
* "idle":"transferring"




| transferStateDetails | 配列[link:#type_astra_stateDetail["type_astra_stateDetail"]] | False  a| 
現在の状態に関する追加の詳細情報（現在の状態に至った理由を含む）。詳細情報がない場合は、この配列は空になります。定義された値は次のとおりです：

* 最小アイテム数：0




| healthState | string | True  a| 
リソースの健全性状態。定義値は次のとおりです：

* 「不確定」 - リソースの状態を判断できません（例えば、接続不良のため）
* 「normal」 - リソースに既知の問題はなく、インターフェース仕様に従ってサービスを提供できます。
* 「警告」：このリソースには既知の問題がありますが、インターフェース仕様に従ってサービスを提供することに支障はありません。
* 「重大」 - リソースに既知の問題があり、インターフェース仕様に従ってサービスを提供できない




| healthStateTransitions | 配列[link:#type_astra_stateTransition["type_astra_stateTransition"]] | True  a| 
特定の定義済み状態からの許可された状態遷移。このリソースでは、以下の状態遷移が可能です：

* "indeterminate"："normal"、"warning"、"critical"
* "normal"："indeterminate"、"warning"、"critical"
* "warning"："indeterminate"、"normal"、"critical"
* "critical"："indeterminate"、"normal"、"warning"




| healthStateDetails | 配列[link:#type_astra_stateDetail["type_astra_stateDetail"]] | True  a| 
現在の状態に関する追加の詳細情報（現在の状態に至った理由を含む）。詳細情報がない場合は、この配列は空になります。定義された値は次のとおりです：

* 最小アイテム数：0




| メタデータ | link:#type_astra_metadata_update["type_astra_metadata_update"] | True  a| 
リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。作成時に指定しない場合、ラベルのないメタデータオブジェクトが作成されます。更新時に指定されていない場合、メタデータオブジェクトのラベル、creationTimestamp および createdBy は、変更なしで保持されます。


|===
[[type_astra_metadata_list]]
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 続行 | string | False  a| 



| カウント | 番号 | False  a| 



| ラベル | 配列[link:#type_astra_label["type_astra_label"]] | False  a| 



| 作成タイムスタンプ | string | False  a| 



| modificationTimestamp | string | False  a| 



| 作成者 | string | False  a| 



| modifiedBy | string | False  a| 

|===
[[invalidParams]]
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 
無効なクエリパラメータの名前



| 理由 | string | True  a| 
クエリパラメータが無効な理由

|===
====