---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-k8s-v1-apps-executionhookoverrides.html 
summary: アプリの実行フックオーバーライドリソースを一覧表示します 
---
= アプリの実行フックオーバーライドリソースを一覧表示します
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/executionHookOverrides`#

コレクション内の一致するすべてのリソースのJSON配列を返します。リクエストで個別のフィールドが指定されている場合、アイテムのJSON配列には、一致する各リソースに対して要求されたフィールドが、指定された順序で含まれます。


CAUTION: この操作は非推奨です。



== パラメータ

[cols="5*"]
|===
| Name | を入力します | 入力 | 必須 | 説明 


| account_id | string | path（パス） | True  a| 
包含するアカウントリソースのID

* 例：{{.Account}}




| app_id | string | path（パス） | True  a| 
含まれるアプリリソースのID



| 含める | string | query | False  a| 
コレクションを一覧表示する際に、どのフィールドを返すかを指定します。

URLの例："include=id"、"include=id,name"

OpenAPI の例："id"



| 制限（ Limit ） | string | query | False  a| 
コレクションを一覧表示する際に返されるリソースの最大数を示します。

URLの例："limit=2"

OpenAPI の例："2"



| フィルタ | string | query | False  a| 
コレクションを一覧表示する際に、リソースを返すためにどのフィールドを一致させる必要があるかを示します。

サポートされているオペレータは次のとおりです：

* eq - 等号
* lt/gt - より小さい/より大きい
* lte/gte - 以下/以上


URLの例："filter=field%20eq%20%27value%27"

OpenAPI の例：「field eq 'value'」

|===


== 応答

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 項目 | 配列[いずれか：link:#executionHookOverride_1_0_get_response_body["executionHookOverride_1.0_get_response_body"]、配列[]] | True  a| 



| メタデータ | link:#type_astra_metadata_list["type_astra_metadata_list"] | True  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-executionHookOverrides",
  "version": "1.0",
  "items": [
    {
      "type": "application/astra-executionHookOverride",
      "version": "1.0",
      "id": "36d06222-bd0c-4897-89c2-c16dd9265e12",
      "executionHookID": "eb863cc6-0d9a-454d-8ef7-81b7cac91929",
      "enabled": "false",
      "appID": "4b43c2f7-bffa-4f60-b595-d98a05b64bc9",
      "metadata": {
        "labels": [],
        "creationTimestamp": "2020-08-06T12:24:52.256624Z",
        "modificationTimestamp": "2020-08-06T12:24:52.256624Z",
        "createdBy": "863feb92-8619-4298-b222-c48a886024f8"
      }
    },
    {
      "type": "application/astra-executionHookOverride",
      "version": "1.0",
      "id": "f8d1ce66-6c0e-4d3a-96c5-a5e76669442d",
      "executionHookID": "eb863cc6-0d9a-454d-8ef7-81b7cac91929",
      "enabled": "false",
      "appID": "36b076ae-b7c4-4e96-a323-ed167ede74ba",
      "metadata": {
        "labels": [],
        "creationTimestamp": "2020-08-06T12:24:52.256624Z",
        "modificationTimestamp": "2020-08-06T12:24:52.256624Z",
        "createdBy": "863feb92-8619-4298-b222-c48a886024f8"
      }
    }
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 応答

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 応答

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 



| invalidParams | 配列[link:#invalidParams["invalidParams"]] | False  a| 
無効なクエリパラメータのリスト

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 応答

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== エラー

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.エラー応答の例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 用語の意味

.定義を参照
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 



| Value | string | True  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。作成時に指定しない場合、ラベルのないメタデータオブジェクトが作成されます。更新時に指定されていない場合、メタデータオブジェクトのラベル、creationTimestamp および createdBy は、変更なしで保持されます。


[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| ラベル | 配列[link:#type_astra_label["type_astra_label"]] | False  a| 



| 作成タイムスタンプ | string | False  a| 



| modificationTimestamp | string | False  a| 



| 作成者 | string | False  a| 



| modifiedBy | string | False  a| 

|===
[role="api-collapsible-fifth-title"]
executionHookOverride_1.0_get_response_body

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 
リソースのメディアタイプ。定義された値は次のとおりです：

* "application/astra-executionHookOverride"




| バージョン | string | True  a| 
リソースのバージョン。定義された値は次のとおりです：

* "1.0"




| ID | string | True  a| 
リソースのグローバル一意識別子。定義された値は次のとおりです：

* UUIDv4スキーマに準拠




| executionHookID | string | True  a| 
実行フックのIDを含むJSON文字列。定義値は次のとおりです：

* Astra識別子スキーマに準拠し、hookType値が「netapp」の実行フックリソースのexecutionHookIDのみを許可します。




| 有効 | string | True  a| 
指定されたアプリケーションに対して実行フックが有効になっているかどうかを示すJSON文字列。定義値は次のとおりです：

* 「true」 - 実行フックが有効になり、指定された順序で実行されます
* 「false」 - 実行フックが無効になっているため実行できません




| appID | string | True  a| 
オーバーライドが関連付けられているアプリケーションの関連IDを含むJSON文字列。定義されている値は次のとおりです：

* Astra識別子スキーマに準拠




| メタデータ | link:#type_astra_metadata_update["type_astra_metadata_update"] | True  a| 
リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。作成時に指定しない場合、ラベルのないメタデータオブジェクトが作成されます。更新時に指定されていない場合、メタデータオブジェクトのラベル、creationTimestamp および createdBy は、変更なしで保持されます。


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 続行 | string | False  a| 



| カウント | 番号 | False  a| 



| ラベル | 配列[link:#type_astra_label["type_astra_label"]] | False  a| 



| 作成タイムスタンプ | string | False  a| 



| modificationTimestamp | string | False  a| 



| 作成者 | string | False  a| 



| modifiedBy | string | False  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 
無効なクエリパラメータの名前



| 理由 | string | True  a| 
クエリパラメータが無効な理由

|===
====