---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-upgrades-.html 
summary: アップグレードを取得する 
---
= アップグレードを取得する
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/upgrades/{upgrade_id}`#

JSON レスポンス ボディに格納されている Upgrade API リソースを返します。



== パラメータ

[cols="5*"]
|===
| Name | を入力します | 入力 | 必須 | 説明 


| account_id | string | path（パス） | True  a| 
包含するアカウントリソースのID

* 例：{{.Account}}




| upgrade_id | string | path（パス） | True  a| 
リストするアップグレード コレクションの ID

|===


== 応答

[source]
----
Status: 200, Returns the stored Upgrade API resource in the JSON response body.
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 
リソースのメディアタイプ。定義された値は次のとおりです：

* "application/astra-upgrade"




| バージョン | string | True  a| 
リソースのバージョン。定義された値は次のとおりです：

* "1.0"
* "1.1"




| ID | string | True  a| 
リソースのグローバル一意識別子。定義された値は次のとおりです：

* UUIDv4スキーマに準拠




| componentName | string | True  a| 
アップグレード可能なソフトウェアの種類名を含むJSON文字列。定義された値は次のとおりです：

* "acc"
* "acs"
* 「trident」
* "kubernetes"




| componentInstance | string | True  a| 
アップグレード可能なコンポーネントのURIを含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：3
* 最大長さ：4095




| componentID | string | True  a| 
アップグレード可能なコンポーネントのグローバルに一意な識別子を含むJSON文字列。定義された値は次のとおりです：

* Astra識別子スキーマに準拠




| upgradeVersion | string | True  a| 
アップグレード可能なソフトウェアイメージファイルのSemVerを含むJSON文字列。定義された値は次のとおりです：

* SemVerスキーマに準拠




| currentVersion | string | True  a| 
アップグレード対象となるエンティティの現在のSemVerを含むJSON文字列。定義された値は次のとおりです：

* SemVerスキーマに準拠




| 依存関係 | array[string] | True  a| 
JSON文字列のJSON配列。各文字列には、このアップグレードを進める前に完了しなければならないアップグレードのUUIDが含まれています。どのアップグレードを前提条件として、どの順序で実行するかを決定するために使用されます。定義された値は次のとおりです：

* Astra識別子スキーマに準拠




| 状態 | string | True  a| 
アップグレードの動作状態を示す値を含むJSON文字列。自動アップグレードが有効になっている場合、アップグレードは「scheduled」の状態から開始されます。それ以外の場合は、アップグレードは「proposed」の状態から開始されます。定義された値は次のとおりです：

* 「利用不可」 - 現時点ではアップグレードはご利用いただけません
* 「提案済み」 - アップグレードは提案されていますが、承認されるまで自動的には実行されません
* 「scheduled」 - アップグレードは承認されていますが、依存関係、時間的制約、または利用可能なリソースの問題により、インストール準備ができていません。
* 「running」 - アップグレードが進行中です
* 「complete」 - アップグレードが完了しました
* 「failed」 - アップグレードが完了しませんでした




| stateDesired | string | True  a| 
「state」の望ましい状態を示す値を含むJSON文字列。このフィールドは、ユーザーがリソースの状態変更を直接要求できる場合にのみ含まれます。定義された値は次のとおりです：

* 「提案済み」 - アップグレードは承認されておらず、実施してはなりません
* 「予定済み」 - アップグレードは承認されており、指定された期間内に実行する必要があります
* 「running」：時間枠に関係なく、アップグレードは直ちに実行する必要があります




| stateDetails | 配列[link:#type_astra_stateDetail["type_astra_stateDetail"]] | True  a| 
現在の「状態」に関する詳細情報を一覧表示する JSON オブジェクトの JSON 配列。詳細情報が利用できない場合、この配列は空になります。

* 最小アイテム数：0




| メタデータ | link:#type_astra_metadata_update["type_astra_metadata_update"] | True  a| 
リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。更新時に指定されていない場合、メタデータオブジェクトのラベル、creationTimestamp および createdBy は、変更されずに保持されます。


|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-upgrade",
  "version": "1.1",
  "id": "aa9a8e88-c012-55b1-b514-7cd94dc79008",
  "componentName": "trident",
  "componentInstance": "https://<dns_name>/accounts/0b311ae7-d89a-4a11-a52c-1349ca090415/topology/v1/clouds/fdda3ff3-a46a-43a4-902e-444fde2baeba/storageBackends/72d19c3c-eb43-4bec-b23e-a228c900aded",
  "componentID": "72d19c3c-eb43-4bec-b23e-a228c900aded",
  "upgradeVersion": "21.07.1",
  "currentVersion": "21.04.1",
  "dependencies": [],
  "state": "scheduled",
  "stateDesired": "scheduled",
  "stateDetails": [],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 応答

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 応答

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 



| invalidParams | 配列[link:#invalidParams["invalidParams"]] | False  a| 
無効なクエリパラメータのリスト

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 応答

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== エラー

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.エラー応答の例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 用語の意味

.定義を参照
[%collapsible]
====
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | False  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 



| Value | string | True  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。更新時に指定されていない場合、メタデータオブジェクトのラベル、creationTimestamp および createdBy は、変更されずに保持されます。


[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| ラベル | 配列[link:#type_astra_label["type_astra_label"]] | False  a| 



| 作成タイムスタンプ | string | False  a| 



| modificationTimestamp | string | False  a| 



| 作成者 | string | False  a| 



| modifiedBy | string | False  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 
無効なクエリパラメータの名前



| 理由 | string | True  a| 
クエリパラメータが無効な理由

|===
====