---
sidebar: sidebar 
api: true 
explorer: true 
permalink: reference/get-accounts-core-v1-users-groups-rolebindings.html 
summary: ユーザーに関連付けられたグループのロールバインディングを一覧表示します 
---
= ユーザーに関連付けられたグループのロールバインディングを一覧表示します
:allow-uri-read: 
:imagesdir: ../media/


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/users/{user_id}/groups/{group_id}/roleBindings`#

コレクション内の一致するすべてのリソースのJSON配列を返します。リクエストで個別のフィールドが指定されている場合、アイテムのJSON配列には、一致する各リソースに対して要求されたフィールドが、指定された順序で含まれます。



[[parameters]]
== パラメータ

[cols="5*"]
|===
| Name | を入力します | 入力 | 必須 | 説明 


| account_id | string | path（パス） | True  a| 
包含するアカウントリソースのID

* 例：{{.Account}}




| user_id | string | path（パス） | True  a| 
含まれるユーザーリソースのID



| group_id | string | path（パス） | True  a| 
包含するグループリソースのID



| 含める | string | query | False  a| 
コレクションを一覧表示する際に、どのフィールドを返すかを指定します。

URLの例："include=id"、"include=id,name"

OpenAPI の例："id"

* 例：accountID、userID、role




| 制限（ Limit ） | string | query | False  a| 
コレクションを一覧表示する際に返されるリソースの最大数を示します。

URLの例："limit=2"

OpenAPI の例："2"



| フィルタ | string | query | False  a| 
コレクションを一覧表示する際に、リソースを返すためにどのフィールドを一致させる必要があるかを示します。

サポートされているオペレータは次のとおりです：

* eq - 等号
* lt/gt - より小さい/より大きい
* lte/gte - 以下/以上


URLの例："filter=field%20eq%20%27value%27"

OpenAPI の例：「field eq 'value'」



| OrderBy | string | query | False  a| 
コレクションを一覧表示する際の、リソースの並び順を示します。

URLの例："orderBy=name"、"orderBy=name%20desc"

OpenAPI の例："name desc"



| スキップします | string | query | False  a| 
コレクションを一覧表示する際にスキップするリソースの数を指定します。

URLの例：「skip=1」

OpenAPI の例："1"



| カウント | string | query | False  a| 
メタデータオブジェクトで返されるリソースの総数。

URLの例："count=true"

OpenAPI の例："true"



| 続行 |  | query | False  a| 
リストの表示を再開するトークンを示します。

URLの例："continue=+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++

OpenAPIの例："+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++</continue>

|===


[[response]]
== 応答

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 項目 | 配列[いずれか：link:#roleBinding_1_1_get_response_body["roleBinding_1.1_get_response_body"]、配列[]] | True  a| 



| メタデータ | link:#type_astra_metadata_list["type_astra_metadata_list"] | True  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-roleBindings",
  "version": "1.1",
  "items": [
    [
      "9fd87309-067f-48c9-a331-527796c14cf3",
      "4c27d25a-9edb-4e85-9438-48dc8e917231",
      "viewer"
    ],
    [
      "9fd87309-067f-48c9-a331-527796c14cf3",
      "dc40a13f-e9b3-4cf5-900f-58de32174390",
      "owner"
    ],
    [
      "9fd87309-067f-48c9-a331-527796c14cf3",
      "c38abd8d-7dae-4659-8382-2e74a58738ba",
      "owner"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


[[response]]
== 応答

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


[[response]]
== 応答

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 



| invalidParams | 配列[link:#invalidParams["invalidParams"]] | False  a| 
無効なクエリパラメータのリスト

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


[[response]]
== 応答

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


[[error]]
== エラー

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.エラー応答の例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


[[definitions]]
== 用語の意味

.定義を参照
[%collapsible]
====
[[type_astra_label]]
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 



| Value | string | True  a| 

|===
[[type_astra_metadata_update]]
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。作成時に指定しない場合、ラベルのないメタデータオブジェクトが作成されます。更新時に指定されていない場合、メタデータオブジェクトのラベル、creationTimestamp および createdBy は、変更なしで保持されます。


[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| ラベル | 配列[link:#type_astra_label["type_astra_label"]] | False  a| 



| 作成タイムスタンプ | string | False  a| 



| modificationTimestamp | string | False  a| 



| 作成者 | string | False  a| 



| modifiedBy | string | False  a| 

|===
[[roleBinding_1_1_get_response_body]]
[role="api-collapsible-fifth-title"]
roleBinding_1.1_get_response_body

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 
リソースのメディアタイプ。定義された値は次のとおりです：

* "application/astra-roleBinding"




| バージョン | string | True  a| 
リソースのバージョン。定義された値は次のとおりです：

* "1.0"
* "1.1"




| ID | string | True  a| 
リソースのグローバル一意識別子。定義された値は次のとおりです：

* UUIDv4スキーマに準拠




| principalType | string | True  a| 
このバインディングが関連付けられているプリンシパルのタイプを表すJSON文字列。定義値は次のとおりです：

* "ユーザー"
* 「group」の場合、principalType「user」には、nil以外のユーザーIDが必要です。principalType「group」の場合、nil以外のグループIDが必要です。




| ユーザーID | string | True  a| 
ユーザーリソース ID を含む JSON 文字列。定義されている値は次のとおりです：

* Astra識別子スキーマに準拠します。作成時に指定されていない場合は、nil UUID が使用されます。作成時に指定できるのは、userID または groupID のみです。




| groupID | string | True  a| 
グループリソースIDを含むJSON文字列。定義されている値は次のとおりです：

* Astra識別子スキーマに準拠します。作成時に指定されていない場合は、nil UUID が使用されます。作成時に指定できるのは、userID または groupID のみです。




| accountID | string | True  a| 
アカウントリソースのIDを含むJSON文字列。作成の場合、これはリクエストURI内のアカウントIDと一致する必要があります。定義値は次のとおりです：

* Astra識別子スキーマに準拠




| ロール | string | True  a| 
定義された4つのロールのいずれかを含むJSON文字列。定義された値は次のとおりです：

* 「viewer」
* "メンバー"
* "admin"
* "所有者"




| roleConstraints | array[string] | False  a| 
役割割り当ての範囲を指定するJSON文字列のJSON配列。定義値は次のとおりです：

* Astraロール制約スキーマに準拠 作成時に指定しない場合、値は「フルスコープ」を表す文字列「*」を含むサイズ1の配列に設定されます。更新時に指定しない場合、値は変更されずに保持されます。空の配列は「スコープなし」を表します。例：
* 
+
= 任意のリソースへのアクセスを許可する："roleConstraints": ["*"]

* 
+
= すべてのリソースへのアクセスを拒否します："roleConstraints": []

* 
+
= 特定の名前空間リソースへのアクセスのみを許可する："roleConstraints": [ "namespaces:id='6fa2f917-f730-41b8-9c15-17f531843b31'" ]

* 
+
= 特定の名前空間とその配下のすべてへのアクセスを許可する："roleConstraints": [ "namespaces:id='6fa2f917-f730-41b8-9c15-17f531843b31'.*"]

* 
+
= 任意のクラウドの任意のクラスターにある「dev」とラベル付けされたすべての名前空間、およびその配下のすべてへのアクセスを許可します："roleConstraints": [ "namespaces:kubernetesLabels='dev.example.com/appname=dev'.*"]

* 
+
= すべての名前空間リソースへのアクセスのみを許可します："roleConstraints": [ "namespaces:*" ]

* 
+
= すべての名前空間リソースとその配下のすべてへのアクセスを許可する："roleConstraints": [ "namespaces:__.__" ]





| メタデータ | link:#type_astra_metadata_update["type_astra_metadata_update"] | True  a| 
リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。作成時に指定しない場合、ラベルのないメタデータオブジェクトが作成されます。更新時に指定されていない場合、メタデータオブジェクトのラベル、creationTimestamp および createdBy は、変更なしで保持されます。


|===
[[type_astra_metadata_list]]
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 続行 | string | False  a| 



| カウント | 番号 | False  a| 



| ラベル | 配列[link:#type_astra_label["type_astra_label"]] | False  a| 



| 作成タイムスタンプ | string | False  a| 



| modificationTimestamp | string | False  a| 



| 作成者 | string | False  a| 



| modifiedBy | string | False  a| 

|===
[[invalidParams]]
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 
無効なクエリパラメータの名前



| 理由 | string | True  a| 
クエリパラメータが無効な理由

|===
====