---
sidebar: sidebar 
api: true 
explorer: true 
permalink: reference/get-accounts-core-v1-users-groups-rolebindings-.html 
summary: ユーザーに関連付けられたグループのロールバインディングを取得します 
---
= ユーザーに関連付けられたグループのロールバインディングを取得します
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/users/{user_id}/groups/{group_id}/roleBindings/{roleBinding_id}`#

JSONレスポンスボディに格納されているロールバインディングAPIリソースを返します。リクエストが /accounts/{account_id}/core/v1/users/{user_id}/roleBindings エンドポイントに対するものである場合、リクエストURL内のユーザーIDと一致するユーザーIDを持つroleBindingリソースのみが読み取りを許可されます。リクエストが /accounts/{account_id}/core/v1/groups/{group_id}/roleBindings に対するものである場合、リクエストURL内のグループIDと一致するグループIDを持つroleBindingリソースのみが読み取りを許可されます。



== パラメータ

[cols="5*"]
|===
| Name | を入力します | 入力 | 必須 | 説明 


| account_id | string | path（パス） | True  a| 
包含するアカウントリソースのID

* 例：{{.Account}}




| user_id | string | path（パス） | True  a| 
含まれるユーザーリソースのID



| group_id | string | path（パス） | True  a| 
包含するグループリソースのID



| roleBinding_id | string | path（パス） | True  a| 
リストするroleBindingコレクションのID

|===


== 応答

[source]
----
Status: 200
----
JSONレスポンスボディに格納されているロールバインディングAPIリソースを返します。リクエストが /accounts/{account_id}/core/v1/users/{user_id}/roleBindings エンドポイントに対するものである場合、リクエストURL内のユーザーIDと一致するユーザーIDを持つroleBindingリソースのみが読み取りを許可されます。リクエストが /accounts/{account_id}/core/v1/groups/{group_id}/roleBindings に対するものである場合、リクエストURL内のグループIDと一致するグループIDを持つroleBindingリソースのみが読み取りを許可されます。

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 
リソースのメディアタイプ。定義された値は次のとおりです：

* "application/astra-roleBinding"




| バージョン | string | True  a| 
リソースのバージョン。定義された値は次のとおりです：

* "1.0"
* "1.1"




| ID | string | True  a| 
リソースのグローバル一意識別子。定義された値は次のとおりです：

* UUIDv4スキーマに準拠




| principalType | string | True  a| 
このバインディングが関連付けられているプリンシパルのタイプを表すJSON文字列。定義値は次のとおりです：

* "ユーザー"
* 「group」の場合、principalType「user」には、nil以外のユーザーIDが必要です。principalType「group」の場合、nil以外のグループIDが必要です。




| ユーザーID | string | True  a| 
ユーザーリソース ID を含む JSON 文字列。定義されている値は次のとおりです：

* Astra識別子スキーマに準拠します。作成時に指定されていない場合は、nil UUID が使用されます。作成時に指定できるのは、userID または groupID のみです。




| groupID | string | True  a| 
グループリソースIDを含むJSON文字列。定義されている値は次のとおりです：

* Astra識別子スキーマに準拠します。作成時に指定されていない場合は、nil UUID が使用されます。作成時に指定できるのは、userID または groupID のみです。




| accountID | string | True  a| 
アカウントリソースのIDを含むJSON文字列。作成の場合、これはリクエストURI内のアカウントIDと一致する必要があります。定義値は次のとおりです：

* Astra識別子スキーマに準拠




| ロール | string | True  a| 
定義された4つのロールのいずれかを含むJSON文字列。定義された値は次のとおりです：

* 「viewer」
* "メンバー"
* "admin"
* "所有者"




| roleConstraints | array[string] | False  a| 
役割割り当ての範囲を指定するJSON文字列のJSON配列。定義値は次のとおりです：

* Astraロール制約スキーマに準拠 作成時に指定しない場合、値は「フルスコープ」を表す文字列「*」を含むサイズ1の配列に設定されます。更新時に指定しない場合、値は変更されずに保持されます。空の配列は「スコープなし」を表します。例：
* 
+
= 任意のリソースへのアクセスを許可する："roleConstraints": ["*"]

* 
+
= すべてのリソースへのアクセスを拒否します："roleConstraints": []

* 
+
= 特定の名前空間リソースへのアクセスのみを許可する："roleConstraints": [ "namespaces:id='6fa2f917-f730-41b8-9c15-17f531843b31'" ]

* 
+
= 特定の名前空間とその配下のすべてへのアクセスを許可する："roleConstraints": [ "namespaces:id='6fa2f917-f730-41b8-9c15-17f531843b31'.*"]

* 
+
= 任意のクラウドの任意のクラスターにある「dev」とラベル付けされたすべての名前空間、およびその配下のすべてへのアクセスを許可します："roleConstraints": [ "namespaces:kubernetesLabels='http://dev.example.com/appname=dev["dev.example.com/appname=dev'.*"]" ]

* 
+
= すべての名前空間リソースへのアクセスのみを許可します："roleConstraints": [ "namespaces:*" ]

* 
+
= すべての名前空間リソースとその配下のすべてへのアクセスを許可する："roleConstraints": [ "namespaces:__.__" ]





| メタデータ | link:#type_astra_metadata_update["type_astra_metadata_update"] | True  a| 
リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。作成時に指定しない場合、ラベルのないメタデータオブジェクトが作成されます。更新時に指定されていない場合、メタデータオブジェクトのラベル、creationTimestamp および createdBy は、変更なしで保持されます。


|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-roleBinding",
  "version": "1.1",
  "id": "a198f052-5cd7-59d3-9f27-9ea32a21fbca",
  "principalType": "user",
  "userID": "4c27d25a-9edb-4e85-9438-48dc8e917231",
  "groupID": "00000000-0000-0000-0000-000000000000",
  "accountID": "9fd87309-067f-48c9-a331-527796c14cf3",
  "role": "viewer",
  "roleConstraints": [
    "*"
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 応答

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 応答

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 



| invalidParams | 配列[link:#invalidParams["invalidParams"]] | False  a| 
無効なクエリパラメータのリスト

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 応答

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== エラー

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.エラー応答の例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 用語の意味

.定義を参照
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 



| Value | string | True  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。作成時に指定しない場合、ラベルのないメタデータオブジェクトが作成されます。更新時に指定されていない場合、メタデータオブジェクトのラベル、creationTimestamp および createdBy は、変更なしで保持されます。


[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| ラベル | 配列[link:#type_astra_label["type_astra_label"]] | False  a| 



| 作成タイムスタンプ | string | False  a| 



| modificationTimestamp | string | False  a| 



| 作成者 | string | False  a| 



| modifiedBy | string | False  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 
無効なクエリパラメータの名前



| 理由 | string | True  a| 
クエリパラメータが無効な理由

|===
====