---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-.html 
summary: アカウントを取得する 
---
= アカウントを取得する
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}`#

JSONレスポンスボディに格納されたAccount APIリソースを返します。



== パラメータ

[cols="5*"]
|===
| Name | を入力します | 入力 | 必須 | 説明 


| account_id | string | path（パス） | True  a| 
一覧表示するアカウントコレクションのID

* 例：{{.Account}}


|===


== 応答

[source]
----
Status: 200, Returns the stored Account API resource in the JSON response body.
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 
リソースのメディアタイプ。定義された値は次のとおりです：

* "application/astra-account"




| バージョン | string | True  a| 
リソースのバージョン。定義された値は次のとおりです：

* "1.0"




| ID | string | True  a| 
リソースのグローバル一意識別子。定義された値は次のとおりです：

* UUIDv4スキーマに準拠




| 名前 | string | True  a| 
アカウント名を含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：1
* 最大長さ：63
* この文字列は、XSS攻撃、Unicode攻撃、ディレクトリトラバーサル攻撃、SQLインジェクション攻撃を防ぐために内部的に検証されます。




| 状態 | string | True  a| 
アカウントの運用状態を示す値を含むJSON文字列。定義された値は次のとおりです：

* 「pending」 - アカウント配下のユーザーおよびロールのリソースのみ変更可能です（デフォルト値）
* 「アクティブ」 - アカウント内のあらゆるリソースに変更を加えることができます
* 「deletePending」- ユーザーはログインできず、データ保護操作は停止され、料金は発生しなくなります




| isEnabled | string | True  a| 
アカウントが有効であることを示すJSON文字列。定義された値は次のとおりです：

* 「false」 - ユーザーはこのアカウントを使用する権限がありません
* 「true」 - ユーザーはこのアカウントを使用することが許可されています




| enabledTimestamp | string | False  a| 
アカウントが最後に有効化された日時を示すタイムスタンプを含むJSON文字列。アカウントが一度も有効化されていない場合、このフィールドは表示されません。定義された値は次のとおりです：

* ISO-8601 Date Time Schemaに準拠




| accountContact | link:#accountContact["accountContact"] | False  a| 
アカウント有効化時にオーナーユーザーを作成するために必要な、ユーザー連絡先情報を含むJSONオブジェクト。



| メタデータ | link:#type_astra_metadata_update["type_astra_metadata_update"] | True  a| 
リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。作成時に指定しない場合、ラベルのないメタデータオブジェクトが作成されます。更新時に指定されていない場合、メタデータオブジェクトのラベル、creationTimestamp および createdBy は、変更なしで保持されます。


|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-account",
  "version": "1.0",
  "id": "666a3f38-d4fa-5b62-a391-a69029758d32",
  "name": "fraught-pines",
  "state": "active",
  "isEnabled": "true",
  "enabledTimestamp": "2020-08-06T12:24:52.256624Z",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 応答

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 応答

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 



| invalidParams | 配列[link:#invalidParams["invalidParams"]] | False  a| 
無効なクエリパラメータのリスト

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 応答

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== エラー

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.エラー応答の例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 用語の意味

.定義を参照
[%collapsible]
====
[role="api-collapsible-fifth-title"]
postalAddress

住所を指定するJSON文字列のコレクションを含むJSONオブジェクト。このキーが存在しない場合、住所が提供されていないことを示します。このキーが存在する場合、含まれている6つのJSON文字列すべてが存在します。何も指定しない場合、文字列は空になります。

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| addressCountry | string | True  a| 
ISO 3166 Alpha-2で規定されている、郵便住所に関連付けられた国名または国コードを含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：2
* 最大長さ：2




| addressLocality | string | True  a| 
郵便番号に関連付けられた地域（例えば、都市）を含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：1
* 最大長さ：63




| addressRegion | string | True  a| 
郵便番号に関連付けられた地域（例えば、州）を含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：1
* 最大長さ：63




| postalCode | string | True  a| 
郵便番号に関連付けられた郵便番号を含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：1
* 最大長さ：31




| streetAddress1を使用したチャンク アップロード署名要求がサポートされるようになりました。 | string | True  a| 
郵便番号に関連付けられた番地を含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：1
* 最大長さ：63




| streetAddress2を使用したチャンク アップロード署名要求がサポートされるようになりました。 | string | False  a| 
オプションの付加的な住所情報（番地、私書箱など）を含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：1
* 最大長さ：63


|===
[role="api-collapsible-fifth-title"]
accountContact

アカウント有効化時にオーナーユーザーを作成するために必要な、ユーザー連絡先情報を含むJSONオブジェクト。

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| firstName | string | True  a| 
ユーザーが指定したフルネーム（名）を含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：1
* 最大長さ：63
* この文字列は、XSS攻撃、Unicode攻撃、ディレクトリトラバーサル攻撃、SQLインジェクション攻撃を防ぐために内部的に検証されます。




| lastName | string | True  a| 
ユーザーが指定した長めの姓を含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：1
* 最大長さ：63
* この文字列は、XSS攻撃、Unicode攻撃、ディレクトリトラバーサル攻撃、SQLインジェクション攻撃を防ぐために内部的に検証されます。




| companyName | string | False  a| 
ユーザーに関連付けられた会社名を含むJSON文字列。このキーが存在しない場合、会社名が提供されていないことを示します。定義された値は次のとおりです：

* 最小長さ：1
* 最大長さ：63
* この文字列は、XSS攻撃、Unicode攻撃、ディレクトリトラバーサル攻撃、SQLインジェクション攻撃を防ぐために内部的に検証されます。




| email | string | True  a| 
ユーザーが指定したメールアドレスを含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：1
* 最大長さ：63




| 電話 | string | False  a| 
ユーザーの電話番号を含むJSON文字列。このキーが存在しない場合、電話番号が提供されていないことを示します。定義された値は次のとおりです：

* 最小長さ：1
* 最大長さ：31




| postalAddress | link:#postalAddress["postalAddress"] | True  a| 
住所を指定するJSON文字列のコレクションを含むJSONオブジェクト。このキーが存在しない場合、住所が提供されていないことを示します。このキーが存在する場合、含まれている6つのJSON文字列すべてが存在します。何も指定しない場合、文字列は空になります。

|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 



| Value | string | True  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。作成時に指定しない場合、ラベルのないメタデータオブジェクトが作成されます。更新時に指定されていない場合、メタデータオブジェクトのラベル、creationTimestamp および createdBy は、変更なしで保持されます。


[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| ラベル | 配列[link:#type_astra_label["type_astra_label"]] | False  a| 



| 作成タイムスタンプ | string | False  a| 



| modificationTimestamp | string | False  a| 



| 作成者 | string | False  a| 



| modifiedBy | string | False  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 
無効なクエリパラメータの名前



| 理由 | string | True  a| 
クエリパラメータが無効な理由

|===
====