---
sidebar: sidebar 
api: true 
explorer: true 
permalink: reference/get-accounts-topology-v1-appbackups-appassets-.html 
summary: アプリケーションバックアップからアプリケーションアセットを取得する 
---
= アプリケーションバックアップからアプリケーションアセットを取得する
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/appBackups/{appBackup_id}/appAssets/{appAsset_id}`#

JSON レスポンス ボディに格納されている Application Asset API リソースを返します。



== パラメータ

[cols="5*"]
|===
| Name | を入力します | 入力 | 必須 | 説明 


| account_id | string | path（パス） | True  a| 
包含するアカウントリソースのID

* 例：{{.Account}}




| appBackup_id | string | path（パス） | True  a| 
含まれるappBackupリソースのID



| appAsset_id | string | path（パス） | True  a| 
リストする appAsset コレクションの ID

|===


== 応答

[source]
----
Status: 200, Returns the stored Application Asset API resource in the JSON response body.
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 
リソースのメディアタイプ。定義された値は次のとおりです：

* "application/astra-appAsset"




| バージョン | string | True  a| 
リソースのバージョン。定義された値は次のとおりです：

* "1.0"
* "1.1"




| ID | string | True  a| 
リソースのグローバル一意識別子。定義された値は次のとおりです：

* UUIDv4スキーマに準拠




| assetType | string | True  a| 
Kubernetesから取得したアセットの種類を示す値を含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：1
* 最大長：254




| 作成タイムスタンプ | string | True  a| 
Kubernetesメタデータが作成された日時を示すタイムスタンプを含むJSON文字列。定義値は次のとおりです：

* ISO-8601 Date Time Schemaに準拠




| GVK | link:#GVK["GVK"] | True  a| 
Kubernetesのグループ/バージョン/種類を含むJSONオブジェクト。



| リソース | link:#type_json["type_json"] | False  a| 
Kubernetesリソース定義の全内容を含むJSONオブジェクト。



| assetID | string | True  a| 
Kubernetesによって割り当てられた識別子を含むJSON文字列。定義値は次のとおりです：

* Astra識別子スキーマに準拠




| ラベル | 配列[link:#labels["ラベル"]] | True  a| 
JSONオブジェクトのJSON配列。各JSONオブジェクトには、アセットに関連付けられたKubernetesラベルが含まれています。詳細情報がない場合は、この配列は空になります。

* 最小アイテム数：0




| assetName | string | True  a| 
Kubernetesによって割り当てられた名前を含むJSON文字列。定義値は次のとおりです：

* 最小長さ：1
* 最大長：254




| namespace | string | False  a| 
Kubernetesによって割り当てられた名前空間を含むJSON文字列。定義値は次のとおりです：

* 最小長さ：1
* 最大長：254




| メタデータ | link:#type_astra_metadata["type_astra_metadata"] | True  a| 
リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astraメタデータスキーマに準拠


|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-appAsset",
  "version": "1.1",
  "id": "6415e851-b820-553b-9432-ebd057d1917d",
  "assetType": "Pod",
  "creationTimestamp": "2020-08-06T12:24:52.256624Z",
  "GVK": {
    "group": "apps",
    "kind": "Pod",
    "version": "v1"
  },
  "assetID": "93ec0c61-d993-4aa1-bb08-f4dcdd5e97f6",
  "labels": [
    {
      "name": "app",
      "value": "mediawiki"
    },
    {
      "name": "pod-template-hash",
      "value": "69c6fcf864"
    }
  ],
  "assetName": "mediawiki-69c6fcf864-2wx6l",
  "namespace": "wiki",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 応答

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 応答

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 



| invalidParams | 配列[link:#invalidParams["invalidParams"]] | False  a| 
無効なクエリパラメータのリスト

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 応答

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== エラー

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.エラー応答の例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 用語の意味

.定義を参照
[%collapsible]
====
[role="api-collapsible-fifth-title"]
GVK

Kubernetesのグループ/バージョン/種類を含むJSONオブジェクト。

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| グループ | string | False  a| 
Kubernetesによって割り当てられたグループ識別子を含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：1
* 最大長：254




| 種類 | string | False  a| 
Kubernetesによって割り当てられた種類識別子を含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：1
* 最大長：254




| バージョン | string | False  a| 
Kubernetesによって割り当てられたバージョン識別子を含むJSON文字列。定義値は次のとおりです：

* 最小長さ：1
* 最大長：254


|===
[role="api-collapsible-fifth-title"]
type_json

Kubernetesリソース定義の全内容を含むJSONオブジェクト。

[role="api-collapsible-fifth-title"]
ラベル

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 
ラベル名を含むJSON文字列。定義済みの値は次のとおりです：

* 最小長さ：1
* 最大長さ：63
* 定義された正規表現は次のとおりです："^([\S.]{1,253}\/)?([a-z0-9A-Z_.-]){1,63}$"




| Value | string | True  a| 
ラベル値を含むJSON文字列。定義済みの値は次のとおりです：

* 最小長さ：1
* 最大長さ：63
* 定義された正規表現は次のとおりです："^([a-z0-9A-Z_.-]){1,63}$"


|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 



| Value | string | True  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata

リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astraメタデータスキーマに準拠


[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| ラベル | 配列[link:#type_astra_label["type_astra_label"]] | True  a| 



| 作成タイムスタンプ | string | True  a| 



| modificationTimestamp | string | True  a| 



| 作成者 | string | True  a| 



| modifiedBy | string | False  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 
無効なクエリパラメータの名前



| 理由 | string | True  a| 
クエリパラメータが無効な理由

|===
====