---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-asups-.html 
summary: ASUPリソースを取得する 
---
= ASUPリソースを取得する
:allow-uri-read: 
:imagesdir: ../media/


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/asups/{asup_id}`#

JSON レスポンス本文に格納された ASUP API リソースを返します。AutoSupport バンドルの「creationState」が「completed」または「partial」の場合、Accept ヘッダーに「_/_」または「application/gzip」を指定することで AutoSupport バンドルをダウンロードできます。



[[parameters]]
== パラメータ

[cols="5*"]
|===
| Name | を入力します | 入力 | 必須 | 説明 


| account_id | string | path（パス） | True  a| 
包含するアカウントリソースのID

* 例：{{.Account}}




| asup_id | string | path（パス） | True  a| 
リストするAutoSupportコレクションのID

|===


[[response]]
== 応答

[source]
----
Status: 200, Returns the stored ASUP API resource in the JSON response body. If the AutoSupport bundle "creationState" is "completed" or "partial", the AutoSupport bundle can be downloaded by specifying an Accept header containing "*/*" or "application/gzip".
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 
リソースのメディアタイプ。定義された値は次のとおりです：

* "application/astra-asup"




| バージョン | string | True  a| 
リソースのバージョン。定義された値は次のとおりです：

* "1.0"




| ID | string | True  a| 
リソースのグローバル一意識別子。定義された値は次のとおりです：

* UUIDv4スキーマに準拠




| creationState | string | True  a| 
AutoSupport バンドルの作成状態を示す値を含むJSON文字列。「completed」および「partial」状態の場合、「_/_」または「application/gzip」を含むAcceptヘッダーを指定してリソースURIに対してGETを実行することで、バンドルをダウンロードできます。定義された値は次のとおりです：

* 「running」 - AutoSupportバンドルの生成は正常に実行されています。
* 「完了」 - AutoSupport バンドル生成が完了しました。
* "partial" - AutoSupport バンドル生成は完了しましたが、一部のデータがバンドルに含まれていませんでした。
* "failed" - AutoSupport バンドル生成が恒久的な障害状態になっています。




| creationStateDetails | 配列[link:#type_astra_stateDetail["type_astra_stateDetail"]] | True  a| 
「creationState」が「partial」または「failed」に移行した理由に関する追加の詳細をリストするJSONオブジェクトのJSON配列。詳細情報がない場合は、この配列は空になります。

* 最小アイテム数：0




| アップロード | string | True  a| 
作成が成功した後にAutoSupportバンドルをアップロードするかどうかを示す値を含むJSON文字列。定義値は次のとおりです：

* 「true」 - AutoSupportバンドルをアップロードします。
* 「false」 - AutoSupportバンドルをアップロードしないでください。




| uploadState | string | False  a| 
要求された場合のAutoSupportバンドルアップロードの状態を示す値を含むJSON文字列。定義値は次のとおりです：

* "pending" - AutoSupportバンドルのアップロードは、AutoSupportバンドルの作成が完了したとき（"creationState"が"running"）にスケジュールされます。
* 「blocked」 - AutoSupportバンドルが作成されなかったため（「creationState」が「failed」）、またはライセンスがないためアップロードがブロックされたため、バンドルのアップロードは試行されませんでした。
* "running" - AutoSupportバンドルのアップロードは正常に実行されています（"creationState"は"completed"または"partial"です）。
* 「完了」- AutoSupportバンドルのアップロードが完了しました。
* "failed" - AutoSupport バンドルのアップロードが恒久的に失敗しています。




| uploadStateDetails | 配列[link:#type_astra_stateDetail["type_astra_stateDetail"]] | False  a| 
「uploadState」が「failed」に移行した理由に関する追加の詳細をリストするJSONオブジェクトのJSON配列。詳細情報がない場合は、この配列は空になります。

* 最小アイテム数：0




| triggerType | string | True  a| 
ASUPリソースの作成をトリガーした要因を示す値を含むJSON文字列。定義値は次のとおりです：

* "manual" - ASUP リソースおよび関連する AutoSupport バンドルは手動で作成されました。
* 「scheduled」 - ASUPリソースおよび関連するAutoSupportバンドルは、設定されたスケジュールに従って作成されました。




| dataWindowStart | string | True  a| 
AutoSupportバンドルデータ収集ウィンドウの開始時刻を示すタイムスタンプを含むJSON文字列。デフォルトは「dataWindowEnd」キー値の24時間前です。「dataWindowEnd」キー値より前に発生する必要があります。最大で、リクエストの現在時刻から7日前までです。定義値は次のとおりです：

* ISO-8601 Date Time Schemaに準拠




| dataWindowEnd | string | True  a| 
AutoSupportバンドルデータ収集ウィンドウの終了時刻を示すタイムスタンプを含むJSON文字列。デフォルトでは、リクエスト時の現在時刻が使用されます。定義された値は次のとおりです：

* ISO-8601 Date Time Schemaに準拠




| メタデータ | link:#type_astra_metadata["type_astra_metadata"] | True  a| 
リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。作成時に指定しない場合、ラベルのないメタデータオブジェクトが作成されます。


|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-asup",
  "version": "1.0",
  "id": "9950003f-a1c7-5ca7-8930-06eec25f60aa",
  "creationState": "completed",
  "creationStateDetails": [],
  "upload": "false",
  "triggerType": "manual",
  "dataWindowStart": "2020-08-05T12:24:00.000000Z",
  "dataWindowEnd": "2020-08-06T12:24:52.000000Z",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


[[response]]
== 応答

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


[[response]]
== 応答

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 



| invalidParams | 配列[link:#invalidParams["invalidParams"]] | False  a| 
無効なクエリパラメータのリスト

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


[[response]]
== 応答

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


[[error]]
== エラー

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.エラー応答の例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


[[definitions]]
== 用語の意味

.定義を参照
[%collapsible]
====
[[additionalDetails]]
[role="api-collapsible-fifth-title"]
additionalDetails

[[type_astra_stateDetail]]
[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | False  a| 

|===
[[type_astra_label]]
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 



| Value | string | True  a| 

|===
[[type_astra_metadata]]
[role="api-collapsible-fifth-title"]
type_astra_metadata

リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。作成時に指定しない場合、ラベルのないメタデータオブジェクトが作成されます。


[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| ラベル | 配列[link:#type_astra_label["type_astra_label"]] | True  a| 



| 作成タイムスタンプ | string | True  a| 



| modificationTimestamp | string | True  a| 



| 作成者 | string | True  a| 



| modifiedBy | string | False  a| 

|===
[[invalidParams]]
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 
無効なクエリパラメータの名前



| 理由 | string | True  a| 
クエリパラメータが無効な理由

|===
====