---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-entitlements.html 
summary: すべてのエンタイトルメントを一覧表示 
---
= すべてのエンタイトルメントを一覧表示
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/entitlements`#

コレクション内の一致するすべてのリソースのJSON配列を返します。リクエストで個別のフィールドが指定されている場合、アイテムのJSON配列には、一致する各リソースに対して要求されたフィールドが、指定された順序で含まれます。



== パラメータ

[cols="5*"]
|===
| Name | を入力します | 入力 | 必須 | 説明 


| account_id | string | path（パス） | True  a| 
包含するアカウントリソースのID

* 例：{{.Account}}




| 含める | string | query | False  a| 
コレクションを一覧表示する際に、どのフィールドを返すかを指定します。

URLの例："include=id"、"include=id,name"

OpenAPI の例："id"

* 例：製品、entitlementType、entitlementValue、割り当て




| 制限（ Limit ） | string | query | False  a| 
コレクションを一覧表示する際に返されるリソースの最大数を示します。

URLの例："limit=2"

OpenAPI の例："2"



| フィルタ | string | query | False  a| 
コレクションを一覧表示する際に、リソースを返すためにどのフィールドを一致させる必要があるかを示します。

サポートされているオペレータは次のとおりです：

* eq - 等号
* lt/gt - より小さい/より大きい
* lte/gte - 以下/以上


URLの例："filter=field%20eq%20%27value%27"

OpenAPI の例：「field eq 'value'」



| OrderBy | string | query | False  a| 
コレクションを一覧表示する際の、リソースの並び順を示します。

URLの例："orderBy=name"、"orderBy=name%20desc"

OpenAPI の例："name desc"



| スキップします | string | query | False  a| 
コレクションを一覧表示する際にスキップするリソースの数を指定します。

URLの例：「skip=1」

OpenAPI の例："1"



| カウント | string | query | False  a| 
メタデータオブジェクトで返されるリソースの総数。

URLの例："count=true"

OpenAPI の例："true"



| 続行 |  | query | False  a| 
リストの表示を再開するトークンを示します。

URLの例："continue=+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++

OpenAPIの例："+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++</continue>

|===


== 応答

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 項目 | 配列[いずれか：link:#entitlement_1_0_get_response_body["entitlement_1.0_get_response_body"]、配列[]] | True  a| 



| メタデータ | link:#type_astra_metadata_list["type_astra_metadata_list"] | True  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-entitlements",
  "version": "1.0",
  "items": [
    [
      "Astra SDS",
      "capacity",
      "2",
      null
    ],
    [
      "Astra Enterprise",
      "clusters",
      "100",
      "5e9fe8f7-4c54-441c-ac94-fd8451f9ca38"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 応答

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 応答

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 



| invalidParams | 配列[link:#invalidParams["invalidParams"]] | False  a| 
無効なクエリパラメータのリスト

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 応答

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== エラー

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.エラー応答の例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 用語の意味

.定義を参照
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 



| Value | string | True  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata

リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astraメタデータスキーマに準拠


[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| ラベル | 配列[link:#type_astra_label["type_astra_label"]] | True  a| 



| 作成タイムスタンプ | string | True  a| 



| modificationTimestamp | string | True  a| 



| 作成者 | string | True  a| 



| modifiedBy | string | False  a| 

|===
[role="api-collapsible-fifth-title"]
entitlement_1.0_get_response_body

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 
リソースのメディアタイプ。定義された値は次のとおりです：

* "application/astra-entitlement"




| バージョン | string | True  a| 
リソースのバージョン。定義された値は次のとおりです：

* "1.0"




| ID | string | True  a| 
リソースのグローバル一意識別子。定義された値は次のとおりです：

* UUIDv4スキーマに準拠




| 割り当て | string | False  a| 
権限が割り当てられているオブジェクトのIDを含むJSON文字列。権限が割り当てられている場合にのみ存在します。文字列の内容はスキーマによって検証されません。



| 製品 | string | False  a| 
ライセンスまたはサブスクリプションから抽出された製品文字列を含むJSON文字列。文字列の内容はスキーマによって検証されません。



| productVersion | string | False  a| 
ライセンスまたはサブスクリプションから抽出されたバージョン文字列を含むJSON文字列。文字列の内容はスキーマによって検証されません。



| entitlementType | string | True  a| 
エンタイトルメントのタイプを含むJSON文字列。これはライセンスまたはサブスクリプションから抽出されます。文字列の内容はスキーマによって検証されません。



| entitlementValue | string | True  a| 
権限に関連付けられた容量を含むJSON文字列。文字列の内容はスキーマによって検証されません。



| entitlementConsumption | string | False  a| 
エンタイトルメントに関連付けられた容量のうち、現在使用されている容量を示すJSON文字列。文字列の内容はスキーマによって検証されません。



| sourceLicense | string | False  a| 
ライセンスの取得元となるライセンスオブジェクトIDを含むJSON文字列。定義された値は次のとおりです：

* Astra識別子スキーマに準拠




| sourceSubscription | string | False  a| 
エンタイトルメントのソースとなるサブスクリプションオブジェクトのIDを含むJSON文字列。定義された値は次のとおりです：

* Astra識別子スキーマに準拠




| validFromTimestamp | string | False  a| 
権利が有効になる日時を示すタイムスタンプを含むJSON文字列。定義された値は次のとおりです：

* ISO-8601 Date Time Schemaに準拠




| validUntilTimestamp | string | False  a| 
権利が無効になった日時を示すタイムスタンプを含むJSON文字列。定義された値は次のとおりです：

* ISO-8601 Date Time Schemaに準拠




| メタデータ | link:#type_astra_metadata["type_astra_metadata"] | True  a| 
リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astraメタデータスキーマに準拠


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 続行 | string | False  a| 



| カウント | 番号 | False  a| 



| ラベル | 配列[link:#type_astra_label["type_astra_label"]] | False  a| 



| 作成タイムスタンプ | string | False  a| 



| modificationTimestamp | string | False  a| 



| 作成者 | string | False  a| 



| modifiedBy | string | False  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 
無効なクエリパラメータの名前



| 理由 | string | True  a| 
クエリパラメータが無効な理由

|===
====