---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-core-v1-hooksources.html 
summary: 新しいフックソースを作成 
---
= 新しいフックソースを作成
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/hookSources`#

作成するフックソースAPIリソースの希望する値を示します。



== パラメータ

[cols="5*"]
|===
| Name | を入力します | 入力 | 必須 | 説明 


| account_id | string | path（パス） | True  a| 
包含するアカウントリソースのID

* 例：{{.Account}}


|===


== 要求の本文

作成するフックソースAPIリソースの希望する値を示します。

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 
リソースのメディアタイプ。定義された値は次のとおりです：

* "application/astra-hookSource"




| バージョン | string | True  a| 
リソースのバージョン。定義された値は次のとおりです：

* "1.0"




| 名前 | string | True  a| 
ユーザーが指定したリソース名を含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：1
* 最大長：63 名前はすべてのフックソースリソース内で一意である必要があります。




| sourceType | string | True  a| 
フックソースのタイプを定義するJSON文字列。定義値は次のとおりです：

* 「script」 - シェルスクリプト。プレーンテキストソースには、バイナリデータまたはキャリッジリターン文字を含めてはなりません。含めた場合はエラーが返されます。




| ソース | string | True  a| 
base64形式で実行するスクリプトを含むJSON文字列。定義されている値は次のとおりです：

* 最小長さ：0
* 最大長さ：131072
* base64エンコードデータスキーマに準拠しています。base64を使用してエンコードした場合、ソース値の最大サイズは128 KiBです。




| description | string | False  a| 
フックソースに関するユーザー指定の説明を含むJSON文字列。定義値は次のとおりです：

* 最小長さ：0
* 最大長さ：511




| メタデータ | link:#type_astra_metadata_update["type_astra_metadata_update"] | False  a| 
リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。作成時に指定しない場合、ラベルのないメタデータオブジェクトが作成されます。更新時に指定されていない場合、メタデータオブジェクトのラベル、creationTimestamp および createdBy は、変更なしで保持されます。


|===
.リクエスト例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-hookSource",
  "version": "1.0",
  "name": "Payroll script",
  "sourceType": "script",
  "source": "ZWNobyAiVkhKaGJuTWdVbWxuYUhSeklRPT0iIHwgYmFzZTY0IC1k",
  "description": "Pre and post hook script for payroll"
}
----
====


== 応答

[source]
----
Status: 201, Returns the newly created hookSource resource in the JSON response body.
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 
リソースのメディアタイプ。定義された値は次のとおりです：

* "application/astra-hookSource"




| バージョン | string | True  a| 
リソースのバージョン。定義された値は次のとおりです：

* "1.0"




| ID | string | True  a| 
リソースのグローバル一意識別子。定義された値は次のとおりです：

* UUIDv4スキーマに準拠




| 名前 | string | True  a| 
ユーザーが指定したリソース名を含むJSON文字列。定義された値は次のとおりです：

* 最小長さ：1
* 最大長：63 名前はすべてのフックソースリソース内で一意である必要があります。




| プライベート | string | True  a| 
ソースフィールドがAPIで公開されるか、意図的に空白のままにされるかを示すJSON文字列。定義値は次のとおりです：

* 「true」 - ソース値は非公開であり、API を通じて公開されることはありません。
* 「false」 - ソース値は非公開ではなく、API を通じて公開されます。




| プリロード済み | string | True  a| 
ソースがプリロードされたかどうかを示すJSON文字列。定義値は次のとおりです：

* 「true」 - ソースはプリロードされています。
* 「false」 - ソースがプリロードされていませんでした。プリロードされたフックソースリソースは読み取り専用です。




| sourceType | string | True  a| 
フックソースのタイプを定義するJSON文字列。定義値は次のとおりです：

* 「script」 - シェルスクリプト。プレーンテキストソースには、バイナリデータまたはキャリッジリターン文字を含めてはなりません。含めた場合はエラーが返されます。




| ソース | string | False  a| 
base64形式で実行するスクリプトを含むJSON文字列。定義されている値は次のとおりです：

* 最小長さ：0
* 最大長さ：131072
* base64エンコードデータスキーマに準拠しています。base64を使用してエンコードした場合、ソース値の最大サイズは128 KiBです。




| sourceMD5Checksumを使用したチャンク アップロード署名要求がサポートされるようになりました。 | string | True  a| 
「source」キーの値に対して計算されたMD5チェックサムを含むJSON文字列。定義されている値は次のとおりです：

* 定義された正規表現は次のとおりです："^([0-9a-fA-F]){32}$"




| description | string | False  a| 
フックソースに関するユーザー指定の説明を含むJSON文字列。定義値は次のとおりです：

* 最小長さ：0
* 最大長さ：511




| メタデータ | link:#type_astra_metadata_update["type_astra_metadata_update"] | True  a| 
リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。作成時に指定しない場合、ラベルのないメタデータオブジェクトが作成されます。更新時に指定されていない場合、メタデータオブジェクトのラベル、creationTimestamp および createdBy は、変更なしで保持されます。


|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-hookSource",
  "version": "1.0",
  "id": "fae6dfbb-ecb8-58ff-a116-6357eb7c956a",
  "name": "Payroll script",
  "private": "false",
  "preloaded": "false",
  "sourceType": "script",
  "source": "ZWNobyAiVkhKaGJuTWdVbWxuYUhSeklRPT0iIHwgYmFzZTY0IC1k",
  "sourceMD5Checksum": "b1a4b8b0144c3f6be553b626130ca145",
  "description": "Pre and post hook script for payroll",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 応答

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 応答

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 



| invalidFields | 配列[link:#invalidFields["invalidFields"]] | False  a| 
無効なリクエストボディフィールドのリスト

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 応答

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 



| invalidFields | 配列[link:#invalidFields["invalidFields"]] | False  a| 
無効なリクエストボディフィールドのリスト

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== 応答

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== エラー

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.エラー応答の例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 用語の意味

.定義を参照
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 



| Value | string | True  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。作成時に指定しない場合、ラベルのないメタデータオブジェクトが作成されます。更新時に指定されていない場合、メタデータオブジェクトのラベル、creationTimestamp および createdBy は、変更なしで保持されます。


[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| ラベル | 配列[link:#type_astra_label["type_astra_label"]] | False  a| 



| 作成タイムスタンプ | string | False  a| 



| modificationTimestamp | string | False  a| 



| 作成者 | string | False  a| 



| modifiedBy | string | False  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 
無効なクエリパラメータの名前



| 理由 | string | True  a| 
クエリパラメータが無効な理由

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 
無効なリクエストボディフィールドの名前



| 理由 | string | True  a| 
リクエスト本文フィールドが無効な理由

|===
====