---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-core-v1-groups.html 
summary: 新しいグループを作成する 
---
= 新しいグループを作成する
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/groups`#

作成するグループ API リソースの希望値を示します。



== パラメータ

[cols="5*"]
|===
| Name | を入力します | 入力 | 必須 | 説明 


| account_id | string | path（パス） | True  a| 
包含するアカウントリソースのID

* 例：{{.Account}}


|===


== 要求の本文

作成するグループ API リソースの希望値を示します。

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 
リソースのメディアタイプ。定義された値は次のとおりです：

* "application/astra-group"




| バージョン | string | True  a| 
リソースのバージョン。定義された値は次のとおりです：

* "1.0"
* "1.1"




| 名前 | string | False  a| 
グループリソースの名前。作成時に指定されていない場合、値は次のように設定されます：

* 最初の共通名（CN）相対識別名（RDN）（authID で見つかった場合）、
* authID、それ以外の場合。更新時に指定がない場合、値は変更されずに保持されます。定義値は次のとおりです：
* 最小長さ：1
* 最大長：2048




| authProvider | string | True  a| 
グループリソースの認証プロバイダー。定義値は次のとおりです：

* "ldap"




| authID | string | True  a| 
LDAPグループの識別名（DN）。定義されている値は次のとおりです：

* 最小長さ：1
* 最大長：2048




| メタデータ | link:#type_astra_metadata_update["type_astra_metadata_update"] | False  a| 
リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。作成時に指定しない場合、ラベルのないメタデータオブジェクトが作成されます。更新時に指定されていない場合、メタデータオブジェクトのラベル、creationTimestamp および createdBy は、変更なしで保持されます。


|===
.リクエスト例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-group",
  "version": "1.1",
  "name": "engineering-group",
  "authProvider": "ldap",
  "authID": "CN=Engineering,CN=Groups,DC=example,DC=com"
}
----
====


== 応答

[source]
----
Status: 201, Returns the newly created group resource in the JSON response body.
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 
リソースのメディアタイプ。定義された値は次のとおりです：

* "application/astra-group"




| バージョン | string | True  a| 
リソースのバージョン。定義された値は次のとおりです：

* "1.0"
* "1.1"




| ID | string | True  a| 
リソースのグローバル一意識別子。定義された値は次のとおりです：

* UUIDv4スキーマに準拠




| 名前 | string | True  a| 
グループリソースの名前。作成時に指定されていない場合、値は次のように設定されます：

* 最初の共通名（CN）相対識別名（RDN）（authID で見つかった場合）、
* authID、それ以外の場合。更新時に指定がない場合、値は変更されずに保持されます。定義値は次のとおりです：
* 最小長さ：1
* 最大長：2048




| authProvider | string | True  a| 
グループリソースの認証プロバイダー。定義値は次のとおりです：

* "ldap"




| authID | string | True  a| 
LDAPグループの識別名（DN）。定義されている値は次のとおりです：

* 最小長さ：1
* 最大長：2048




| メタデータ | link:#type_astra_metadata_update["type_astra_metadata_update"] | True  a| 
リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。作成時に指定しない場合、ラベルのないメタデータオブジェクトが作成されます。更新時に指定されていない場合、メタデータオブジェクトのラベル、creationTimestamp および createdBy は、変更なしで保持されます。


|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-group",
  "version": "1.1",
  "id": "77754011-b93f-515e-a145-5a343aecdece",
  "name": "engineering-group",
  "authProvider": "ldap",
  "authID": "CN=Engineering,CN=Groups,DC=example,DC=com",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 応答

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 



| invalidFields | 配列[link:#invalidFields["invalidFields"]] | False  a| 
無効なリクエストボディフィールドのリスト

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== 応答

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/14",
  "title": "Unauthorized access",
  "detail": "The user isn't enabled.",
  "status": "403"
}
----
====


== 応答

[source]
----
Status: 406, Not acceptable
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/32",
  "title": "Unsupported content type",
  "detail": "The response can't be returned in the requested format.",
  "status": "406"
}
----
====


== 応答

[source]
----
Status: 500, Internal server error
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 

|===
.回答例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/34",
  "title": "Internal server error",
  "detail": "The server was unable to process this request.",
  "status": "500"
}
----
====


== エラー

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| を入力します | string | True  a| 



| タイトル | string | True  a| 



| 詳細 | string | True  a| 



| ステータス | string | True  a| 



| correlationID | string | False  a| 



| invalidParams | 配列[link:#invalidParams["invalidParams"]] | False  a| 
無効なクエリパラメータのリスト

|===
.エラー応答の例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/7",
  "title": "Invalid JSON payload",
  "detail": "The request body is not valid JSON.",
  "status": "400"
}
----
====


== 用語の意味

.定義を参照
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 



| Value | string | True  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

リソースに関連付けられた、クライアントおよびサービス指定のメタデータ。定義された値は次のとおりです：

* Astra メタデータスキーマに準拠します。作成時に指定しない場合、ラベルのないメタデータオブジェクトが作成されます。更新時に指定されていない場合、メタデータオブジェクトのラベル、creationTimestamp および createdBy は、変更なしで保持されます。


[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| ラベル | 配列[link:#type_astra_label["type_astra_label"]] | False  a| 



| 作成タイムスタンプ | string | False  a| 



| modificationTimestamp | string | False  a| 



| 作成者 | string | False  a| 



| modifiedBy | string | False  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 
無効なクエリパラメータの名前



| 理由 | string | True  a| 
クエリパラメータが無効な理由

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Name | を入力します | 必須 | 説明 


| 名前 | string | True  a| 
無効なリクエストボディフィールドの名前



| 理由 | string | True  a| 
リクエスト本文フィールドが無効な理由

|===
====