---
sidebar: sidebar 
permalink: workflows/wf_clone_app_snapshot.html 
keywords:  
summary: Snapshotからクローニングして新しいアプリケーションを作成できます。 
---
= スナップショットからアプリケーションをクローニングします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Snapshotからクローニングして新しいアプリケーションを作成できます。



== 作業を開始する前に

このワークフローについては、次の点に注意してください。

* アプリケーションスナップショットが使用されます
* クローニング処理は同じクラスタ内で実行されます



NOTE: アプリケーションを別のクラスタにクローニングするには、 JSON 入力の「 clusterId 」パラメータを環境に応じて更新する必要があります。



== 手順1：クローニングするアプリケーションを選択

ワークフローを実行 link:wf_list_man_apps.html["アプリを表示します"] をクリックし、クローニングするアプリケーションを選択します。アプリケーションのクローニングに使用される REST 呼び出しには、いくつかのリソース値が必要です。



== 手順2：使用するSnapshotを選択する

ワークフローを実行 link:wf_list_snapshots.html["Snapshot を一覧表示します"] をクリックし、使用する Snapshot を選択します。



== ステップ3：アプリケーションのクローンを作成する

次の REST API 呼び出しを実行します。

.HTTPメソッドとエンドポイント
このREST API呼び出しでは、次のメソッドとエンドポイントを使用します。

[cols="25,75"]
|===
| HTTP メソッド | パス 


| 投稿（ Post ） | /accounts /｛account_id｝/k8s/v2/apps 
|===
.追加の入力パラメータ
すべての REST API 呼び出しに共通するパラメータに加えて、この手順の curl の例では次のパラメータも使用されます。

[cols="25,10,10,55"]
|===
| パラメータ | を入力します | 必須 | 説明 


| JSON | ボディ（ Body ） | はい。 | クローニングされたアプリケーションのパラメーターを提供します。以下の例を参照してください。 
|===
.curl の例： Snapshot からアプリケーションをクローニングします
[source, curl]
----
curl --request POST \
--location "'https://astra.netapp.io/accounts/$ACCOUNT_ID/k8s/v2/apps" \
--include \
--header "Content-Type: application/astra-app+json" \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data  @JSONinput
----
.JSON の入力例
[source, json]
----
{
  "type": "application/astra-app",
  "version": "2.0",
  "name": "mysql-clone2",
  "clusterID": "30880586-d579-4d27-930f-a9633e59173b",
  "sourceClusterID": "30880586-d579-4d27-930f-a9633e59173b",
  "namespace": "mysql",
  "snapshotID": "e24515bd-a28e-4b28-b832-f3c74dbf32fb"
}
----