---
sidebar: sidebar 
permalink: workflows/wf_delete_backup.html 
keywords:  
summary: アプリケーションに関連付けられているバックアップを削除することができます。 
---
= バックアップを削除します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
アプリケーションに関連付けられているバックアップを削除することができます。



=== 作業を開始する前に

次の情報が必要です。

* バックアップを所有するアプリケーションのID。必要に応じて、ワークフローを使用できます link:wf_list_man_apps.html["アプリを表示します"] アプリケーションを検索します。
* 削除するバックアップの ID 。必要に応じて、ワークフローを使用できます link:wf_list_backups.html["バックアップをリスト表示します"] をクリックしてください。




=== 1. バックアップを削除します

次の REST API 呼び出しを実行します。


NOTE: 障害が発生したバックアップは、次に示すオプションの要求ヘッダーを使用して強制的に削除できます。

[cols="25,75"]
|===
| HTTP メソッド | パス 


| 削除 | /accounts /｛account_id｝/k8s/v1/apps/｛app_id｝/appBackups /｛appBackup_id｝ 
|===


===== 追加の入力パラメータ

すべての REST API 呼び出しに共通するパラメータに加えて、この手順の curl の例では次のパラメータも使用されます。

[cols="25,10,10,55"]
|===
| パラメータ | を入力します | 必須 | 説明 


| アプリケーションID | パス | はい。 | バックアップを所有する管理アプリケーションを指定します。 


| バックアップ ID | パス | はい。 | 削除するバックアップを指定します。 


| 強制的に削除します | ヘッダー | いいえ | 失敗したバックアップを強制的に削除する場合に使用します。 
|===


===== curl の例：アプリケーションのバックアップを 1 つ削除します

[source, curl]
----
curl --location -i --request DELETE 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/apps/<APP_ID>/appBackups/<BACKUP_ID>' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== curl の例： force オプションを使用して、アプリケーションのバックアップを 1 つ削除します

[source, curl]
----
curl --location -i --request DELETE 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/apps/<APP_ID>/appBackups/<BACKUP_ID>' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>' --header 'Force-Delete: true'
----