---
sidebar: sidebar 
permalink: workflows/wf_list_unman_apps.html 
keywords:  
summary:  
---
= アンマネージアプリケーションをリストします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Astra で現在管理されていないアプリケーションをリストできます。これは、管理対象のアプリケーションを選択する際に行うことができます。


NOTE: これらのワークフローで使用されている REST エンドポイントは、すべての Astra アプリケーションをデフォルトで返します。API 呼び出しで「 filter 」クエリーパラメータを使用して、アンマネージアプリケーションのみを返すように要求できます。代わりに、フィルタパラメータを省略してすべてのアプリケーションを返し、出力の「 anagedState 」フィールドを調べて、「 unmanaged 」状態のアプリケーションを判別することもできます。



== managedState が unmanaged のアプリケーションのみをリストします

このワークフローでは 'filter' クエリー・パラメータを使用して ' 管理対象外のアプリケーションのみを返します



=== 1. 管理対象外のアプリケーションを一覧表示します

次の REST API 呼び出しを実行します。

[cols="25,75"]
|===
| HTTP メソッド | パス 


| 取得 | /account/{accountID}/topology/v1/apps の順で指定します 
|===


===== 追加の入力パラメータ

すべての REST API 呼び出しに共通するパラメータに加えて、この手順の curl の例では次のパラメータも使用されます。

[cols="25,10,10,55"]
|===
| パラメータ | を入力します | 必須 | 説明 


| フィルタ | クエリ | いいえ | フィルタを使用して、どのアプリケーションを返すかを指定します。 


| 含める | クエリ | いいえ | 必要に応じて、応答で返す値を選択します。 
|===


===== curl の例：アンマネージアプリケーションの名前、 ID 、および managedState を返します

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/apps?filter=managedState%20eq%20'unmanaged'&include=name,id,managedState' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== JSON 出力例

[source, json]
----
{
  "items": [
    [
      "maria",
      "eed19f78-0884-4792-bb7a-313258c6b0b1",
      "unmanaged"
    ],
    [
      "test-postgres-app",
      "1ee6235b-cda1-45cb-8d4c-630bdb8b41a5",
      "unmanaged"
    ],
    [
      "postgres1-postgresql",
      "e591ee59-ea90-4a9f-8e6c-d2b6e8647096",
      "unmanaged"
    ],
    [
      "kube-system",
      "077a2f73-4b51-4d04-8c6c-f63b3b069755",
      "unmanaged"
    ],
    [
      "trident",
      "5b6fc28f-e308-4653-b9d2-6d66a764d2e1",
      "unmanaged"
    ],
    [
      "postgres1-postgresql-clone",
      "06be05c5-763e-4d73-bd06-1f27f5f2e130",
      "unmanaged"
    ]
  ],
  "metadata": {}
}
----


== すべてのアプリケーションをリストし、管理対象外のアプリケーションを選択します

このワークフローはすべてのアプリケーションを返します。出力を調べて、どちらが管理対象外であるかを確認する必要があります。



=== 1. すべてのアプリケーションを一覧表示します

次の REST API 呼び出しを実行します。

[cols="25,75"]
|===
| HTTP メソッド | パス 


| 取得 | /account/{accountID}/topology/v1/apps の順で指定します 
|===


===== 追加の入力パラメータ

すべての REST API 呼び出しに共通するパラメータに加えて、この手順の curl の例では次のパラメータも使用されます。

[cols="25,10,10,55"]
|===
| パラメータ | を入力します | 必須 | 説明 


| 含める | クエリ | いいえ | 必要に応じて、応答で返す値を選択します。 
|===


===== curl の例：すべてのアプリケーションのすべてのデータを返します

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/apps' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== curl の例：すべてのアプリケーションの名前、 ID 、 managedState を返します

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/apps?include=name,id,managedState' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== JSON 出力例

[source, json]
----
{
  "items": [
    [
      "maria",
      "eed19f78-0884-4792-bb7a-313258c6b0b1",
      "unmanaged"
    ],
    [
      "mariadb-mariadb",
      "8da20fff-c69c-4170-bb0d-e4f91c5a1333",
      "managed"
    ],
    [
      "test-postgres-app",
      "1ee6235b-cda1-45cb-8d4c-630bdb8b41a5",
      "unmanaged"
    ],
    [
      "postgres1-postgresql",
      "e591ee59-ea90-4a9f-8e6c-d2b6e8647096",
      "unmanaged"
    ],
    [
      "kube-system",
      "077a2f73-4b51-4d04-8c6c-f63b3b069755",
      "unmanaged"
    ],
    [
      "trident",
      "5b6fc28f-e308-4653-b9d2-6d66a764d2e1",
      "unmanaged"
    ],
    [
      "postgres1-postgresql-clone",
      "06be05c5-763e-4d73-bd06-1f27f5f2e130",
      "unmanaged"
    ],
    [
      "davidns-postgres-app",
      "11e046b7-ec64-4184-85b3-debcc3b1da4d",
      "managed"
    ]
  ],
  "metadata": {}
}
----


=== 2. 管理されていないアプリケーションを選択します

API 呼び出しの出力を確認し、「 unmanaged 」に等しい「 anagedState 」を持つアプリケーションを手動で選択します。
