---
sidebar: sidebar 
permalink: workflows/wf_manage_app.html 
keywords:  
summary: 特定のネームスペースですでにAstraが認識しているアプリケーションに基づいて、管理アプリケーションを作成できます。アプリケーションをAstraで管理または定義した場合、バックアップとスナップショットを作成してアプリケーションを保護できます。 
---
= アプリを管理します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
特定のネームスペースですでにAstraが認識しているアプリケーションに基づいて、管理アプリケーションを作成できます。アプリケーションをAstraで管理または定義した場合、バックアップとスナップショットを作成してアプリケーションを保護できます。



== 手順1：ネームスペースを選択する

ワークフローを実行 link:../workflows/wf_list_namespaces.html["ネームスペースを表示します"] ネームスペースを選択します。



== 手順2：クラスタを選択する

ワークフローを実行 link:../workflows_infra/wf_list_clusters.html["クラスタをリストします"] をクリックし、クラスタを選択します。



== ステップ3：アプリケーションを管理する

アプリケーションを管理するために次のREST API呼び出しを実行します。

.HTTPメソッドとエンドポイント
このREST API呼び出しでは、次のメソッドとエンドポイントを使用します。

[cols="25,75"]
|===
| HTTP メソッド | パス 


| 投稿（ Post ） | /accounts /｛account_id｝/k8s/v2/apps 
|===
.追加の入力パラメータ
すべての REST API 呼び出しに共通するパラメータに加えて、この手順の curl の例では次のパラメータも使用されます。

[cols="25,10,10,55"]
|===
| パラメータ | を入力します | 必須 | 説明 


| JSON | ボディ（ Body ） | はい。 | 管理対象アプリケーションを識別するために必要なパラメータを提供します。以下の例を参照してください。 
|===
.curl の例：アプリケーションの管理
[source, curl]
----
curl --request POST \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/k8s/v2/apps" \
--include \
--header "Content-Type: application/astra-app+json" \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data @JSONinput
----
.JSON の入力例
[source, json]
----
{
  "clusterID": "7ce83fba-6aa1-4e0c-a194-26e714f5eb46",
  "name": "subtext",
  "namespaceScopedResources": [{"namespace": "kube-matrix"}],
  "type": "application/astra-app",
  "version": "2.0"
}
----