---
sidebar: sidebar 
permalink: workflows/workflows_before.html 
keywords:  
summary:  
---
= 作業を開始する前に
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
これらのワークフローは、 Astra 管理対象クラスタ内でアプリケーションを管理する際に使用できます。


NOTE: これらのワークフローは、ネットアップがいつでも拡張および強化できるため、定期的に確認する必要があります。



== 一般的な準備

いずれかの Astra ワークフローを使用する前に、を確認してください link:../get-started/prepare_to_use_workflows.html["ワークフローを使用する準備をします"]。



== ワークフローのカテゴリ

管理ワークフローは、目的のワークフローを見つけやすくするために、さまざまなカテゴリに分類されています。

[cols="25,75"]
|===
| カテゴリ | 説明 


| アプリケーション制御 | これらのワークフローでは、管理対象アプリケーションと管理対象外アプリケーションを制御できます。アプリをリスト表示したり、管理アプリを作成および削除したりできます。 


| アプリケーションの保護 | これらのワークフローを使用して、 Snapshot とバックアップを通じて管理対象アプリケーションを保護することができます。 


| アプリケーションのクローニングとリストア | ここでは、管理対象アプリケーションのクローニングとリストアのワークフローについて説明します。 


| サポート | アプリケーションと一般的な Kubernetes 環境をデバッグおよびサポートするためのワークフローがいくつかあります。 
|===


== その他の考慮事項については

管理ワークフローを使用する場合は、さらにいくつかの点を考慮する必要があります。



=== アプリケーションのクローンを作成します

アプリケーションのクローニングでは、いくつかの点を考慮する必要があります。以下に、 JSON 入力のパラメータを示します。

ソースクラスタの識別子:: 「 ourceClusterID 」の値は、元のアプリケーションがインストールされているクラスタを常に識別します。
クラスタ ID:: 「 ClusterId 」の値は、新しいアプリケーションをインストールするクラスタを識別します。
+
--
* 同じクラスタ内でクローニングする場合、「 ClusterId 」と「 ourceClusterID 」には同じ値があります。
* クラスタ間でクローンを作成する場合 ' 2 つの値は異なる値であり 'ClusterId' はターゲット・クラスタの ID である必要があります


--
ネームスペース:: 「 namespace 」の値は、元のソースアプリケーションとは異なる値にする必要があります。さらに、クローンのネームスペースを作成できず、 Astra がそのクローンを作成します。
バックアップとスナップショット:: オプションで 'backupid' または 'napshotID' パラメータを使用して ' 既存のバックアップまたはスナップショットからアプリケーションのクローンを作成できますバックアップまたはスナップショットを指定しない場合は、まずアプリケーションのバックアップを作成し、次にバックアップからクローンを作成します。




==== アプリケーションの復元

アプリケーションをリストアする際に考慮すべき事項をいくつか示します。

* アプリケーションのリストアは、クローニング処理とほぼ同じです。
* アプリケーションをリストアするときは、バックアップまたはスナップショットを指定する必要があります。

