---
sidebar: sidebar 
permalink: python/astra_toolkits.html 
keywords:  
summary:  
---
= NetApp Astra Control Python SDK
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Astra Control Python SDK は、 Astra Control の導入を自動化するために使用できるオープンソースパッケージです。また、このパッケージは、独自の自動化プラットフォームを作成する際に、おそらく Astra Control REST API について学ぶ際の貴重な資料となります。


NOTE: 簡単にするために、このページの以降の部分では、 NetApp Astra Control Python SDK を * SDK と呼びます。



== 関連する 2 つのソフトウェアツール

SDK には、 Astra Control REST API にアクセスするときに異なる抽象化レベルで動作する 2 つの異なる関連ツールが含まれています。



==== Astra SDK

Astra SDK は、コアプラットフォーム機能を提供します。基盤となる REST API 呼び出しを抽象化する一連の Python クラスが含まれています。このクラスは、アプリケーション、バックアップ、 Snapshot 、クラスタなど、さまざまな Astra Control リソースに対する管理操作をサポートしています。

Astra SDK はパッケージの一部であり、単一の「 astrasdk.py 」ファイルで提供されています。このファイルを環境にインポートし、クラスを直接使用できます。


NOTE: NetApp Astra Control Python SDK * （または SDK のみ）は、パッケージ全体の名前です。*Astra SDK* は、単一ファイル「 astrasdk.py 」の中核的な Python クラスを指します。



==== Toolkit スクリプト

Astra SDK ファイルに加えて 'toolkit.py スクリプトも利用できますこのスクリプトは、 Python 関数として内部的に定義されている個別の管理アクションにアクセスできるようにすることで、抽象化のレベルを高めて動作します。このスクリプトは、 Astra SDK をインポートし、必要に応じてクラスに呼び出します。



== にアクセスする方法

SDK には、次の方法でアクセスできます。



==== Python パッケージ

SDK は、から入手できます https://pypi.org/["Python パッケージインデックス"^] 名前の下にある * NetApp-Astra - ツールキット * 。パッケージにはバージョン番号が割り当てられており、必要に応じて更新が続行されます。パッケージを環境にインストールするには、 * PIP * パッケージ管理ユーティリティを使用する必要があります。

を参照してください https://pypi.org/project/netapp-astra-toolkits/["PyPi ： NetApp Astra Control Python SDK"^] を参照してください。



==== GitHub ソースコード

SDK ソースコードは GitHub からも入手できます。リポジトリには次のものが含まれます。

* `astrasdk.py (Python クラスを含む Astra SDK)
* `toolkit.py ( より高度な関数ベースのスクリプト )
* インストール要件と手順の詳細
* インストールスクリプト
* その他のドキュメント


のクローンを作成できます https://github.com/NetApp/netapp-astra-toolkits["GitHub ： NetApp / NetApp-Astra - ツールキット"^] ローカル環境へのリポジトリ。



== インストールと基本的な要件

パッケージのインストールおよび使用準備の一環として、いくつかのオプションと要件を考慮する必要があります。



==== インストールオプションの概要

次のいずれかの方法で SDK をインストールできます。

* Pip を使用して、 PyPI のパッケージを Python 環境にインストールします
* Git Hub リポジトリをクローニングし、次のいずれかを実行します。
+
** パッケージを Docker コンテナとして導入（必要なものをすべて含む）
** Python クライアントコードにアクセスできるように、 2 つのコア Python ファイルをコピーします




詳細については、 PyPi および GitHub のページを参照してください。



==== Astra Control 環境の要件

Astra SDK の Python クラスを直接使用する場合も、「 toolkit.py 」スクリプトの関数を使用する場合も、最終的には Astra Control 配置で REST API にアクセスすることになります。そのため、 API トークンを持つ Astra アカウントが必要になります。を参照してください link:../get-started/before_get_started.html["作業を開始する前に"] 詳細については、このドキュメントの「 * はじめに * 」セクションの他のページを参照してください。



==== NetApp Astra Control Python SDK の要件

SDK には、ローカル Python 環境に関連するいくつかの前提条件があります。たとえば、 Python 3.5 以降を使用する必要があります。また、必要な Python パッケージもいくつかあります。詳細については、 GitHub リポジトリページまたは PyPI パッケージページを参照してください。



== 役立つリソースの概要

ここでは、開始するために必要なリソースの概要を示します。

* https://pypi.org/project/netapp-astra-toolkits/["PyPi ： NetApp Astra Control Python SDK"^]
* https://github.com/NetApp/netapp-astra-toolkits["GitHub ： NetApp / NetApp-Astra - ツールキット"^]

