---
sidebar: sidebar 
permalink: endpoints/resources.html 
keywords:  
summary:  
---
= リソース
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
REST API のリソースを使用して、 Astra の導入の管理を自動化できます。各リソースは、 1 つ以上のエンドポイントを介してアクセスされます。ここでは、自動化の導入計画の一環として役立つ、これらのリソースの概要を示します。

を参照してください link:../reference/api_reference.html["API リファレンス"] を参照してください。



== Astra REST API のリソースの概要

Astra REST API に用意されているリソースエンドポイントは、 3 つのカテゴリに分類されています



===== コアリソース

コアリソースエンドポイントは、 Astra ランタイム環境の確立と保守に必要な基盤サービスを提供します。エンドポイントには次のものがあり

* クレデンシャル
* イベント
* 通知
* ロールのバインド
* トークン
* 未読通知
* ユーザ




===== アプリケーションリソースの管理

管理対象アプリケーションリソースエンドポイントは、管理対象の Kubernetes アプリケーションへのアクセスを提供します。エンドポイントには次のものがあり

* アプリケーションアセット
* アプリケーションのバックアップ
* アプリケーションスナップショット
* マネージドアプリケーション
* スケジュール




===== トポロジリソース

トポロジリソースエンドポイントは、管理対象外のアプリケーションとストレージリソースへのアクセスを提供します。エンドポイントには次のものがあり

* アプリケーション
* ボリューム




== アクセスパスと URL の形式

Astra リソースへのアクセスに使用されるパスと完全な URL の形式は、いくつかの値に基づいています。を参照してください link:../rest-core/url_format.html["URL 形式"] を参照してください。
