---
sidebar: sidebar 
permalink: endpoints/resources.html 
keywords:  
summary:  
---
= リソースとエンドポイント
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Astra Control REST API のリソースを使用すると、 Astra の導入を自動化できます。各リソースは、 1 つ以上のエンドポイントを介してアクセスされます。ここでは、自動化の導入計画の一環として使用できる REST リソースの概要を示します。


NOTE: Astra Control リソースへのアクセスに使用されるパスと完全な URL の形式は、いくつかの値に基づいています。を参照してください link:../rest-core/url_format.html["URL 形式"] を参照してください。も参照してください  Astra のリソースとエンドポイントの使用方法の詳細については、を参照してください。



== Astra Control REST のリソースとエンドポイント

Astra Control REST API に用意されているプライマリリソースエンドポイントは、 3 つのカテゴリに分類されています。各リソースは、特定の場所を除いて、すべての CRUD 操作（作成、読み取り、更新、削除）を使用してアクセスできます。



=== コアリソース

コアリソースエンドポイントは、 Astra ランタイム環境の確立と保守に必要な基盤サービスを提供します。

ASUP:: ASUP リソースには、ネットアップサポートに転送される AutoSupport バンドルが表示されます。
クレデンシャル:: クレデンシャルリソースには、 Astra ユーザ、クラスタ、バケット、ストレージバックエンドで使用できるセキュリティ関連の情報が含まれています。
使用権:: 使用権リソースは、アクティブなライセンスとサブスクリプションに基づいて、アカウントで使用可能な機能と容量を表します。
イベント:: イベントリソースは、通知として分類されたサブセットも含めて、システムで発生するすべてのイベントを表します。
フィーチャー（ Feature ）:: 機能リソースは、選択した Astra 機能を表します。この機能を照会することで、システムで有効になっているか無効になっているかを確認できます。アクセスは読み取り専用に制限されます。
使用許諾:: ライセンスリソースは、 Astra アカウントで使用可能なライセンスを表します。
通知:: 通知リソースは、通知の送信先を持つ Astra イベントを表します。アクセスはユーザ単位で提供されます。
ロールのバインド:: ロールバインドリソースは ' 特定のユーザーとアカウントのペア間の関係を表します2 つの間のリンクに加えて、特定のロールを通じて各に一連の権限が指定されます。
設定:: 設定リソースは、特定のアストラアカウントの機能を説明するキーと値のペアの集まりです。
サブスクリプション。:: サブスクリプションリソースは、 Astra アカウントのアクティブなサブスクリプションです。
トークン:: トークンリソースとは、プログラムによって Astra Control REST API にアクセスできるトークンのことです。
未読通知:: 未読通知リソースは、特定のユーザーに割り当てられているがまだ読み込まれていない通知を表します。
ユーザ:: ユーザリソースは、 Astra を使用するユーザで、定義したロールに基づいてシステムにアクセスできる。




=== アプリケーションリソースの管理

管理対象アプリケーションリソースエンドポイントは、管理対象の Kubernetes アプリケーションへのアクセスを提供します。

アプリケーションアセット:: アプリケーションアセットリソースは、 Astra アプリケーションの管理に必要な状態情報の内部コレクションです。
アプリケーションのバックアップ:: アプリケーションのバックアップリソースは、管理対象アプリケーションのバックアップを表します。
アプリケーションスナップショット:: アプリケーションスナップショットリソースは、管理対象アプリケーションのスナップショットを表します。
マネージドアプリケーション:: マネージドアプリケーションリソースは、 Astra が管理する Kubernetes アプリケーションを表しています。
スケジュール:: スケジュールリソースとは、データ保護ポリシーの一部として管理対象アプリケーションにスケジュールされているデータ保護処理のことです。




=== トポロジリソース

トポロジリソースエンドポイントは、管理対象外のアプリケーションとストレージリソースへのアクセスを提供します。

アプリケーション:: アプリケーションリソースは、 Astra が管理していないアプリケーションも含め、 Kubernetes のすべてのアプリケーションを表します。
バケット:: バケットリソースは、 Astra が管理するアプリケーションのバックアップを保存するために使用する S3 クラウドバケットです。
クラウド:: クラウドリソースとは、アストラクライアントから接続してクラスタやアプリケーションを管理できるクラウドのことです。
クラスタ:: クラスタリソースは Kubernetes で管理されない Kubernetes クラスタを表します。
管理対象クラスタ:: 管理対象クラスタリソースは、 Kubernetes で現在管理されている Kubernetes クラスタを表します。
ストレージバックエンド:: ストレージバックエンドリソースは、 Astra が管理するクラスタとアプリケーションで使用できるストレージサービスのプロバイダです。
ストレージクラス:: ストレージクラスのリソースは、さまざまなクラスやタイプのストレージを表しており、特定の管理対象クラスタで使用できます。
ボリューム:: ボリュームリソースは、管理対象アプリケーションに関連付けられた Kubernetes ストレージボリュームを表します。




== その他のリソースとエンドポイント

Astra の導入をサポートするために使用できる追加のリソースとエンドポイントがいくつかあります。


NOTE: これらのリソースとエンドポイントは、現在のところ、 Astra Control REST API リファレンスドキュメントに含まれていません。

OpenAPI:: OpenAPI エンドポイントは、現在の OpenAPI JSON ドキュメントおよびその他の関連リソースへのアクセスを提供します。
OpenMetrics:: OpenMetrics エンドポイントは、 OpenMetrics リソースを介してアカウントメトリックへのアクセスを提供します。サポートは、 Astra Control Center 導入モデルで利用できます。

