---
sidebar: sidebar 
permalink: get-started/get_api_token.html 
keywords: token, obtain token 
summary: Astra Control REST API を使用するには、 Astra API トークンを取得する必要があります。 
---
= API トークンを取得します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Astra Control REST API を使用するには、 Astra API トークンを取得する必要があります。



== はじめに

API トークンは、 Astra の呼び出し元を識別し、すべての REST API 呼び出しに含める必要があります。

* Astra Web ユーザインターフェイスを使用して、 API トークンを生成できます。
* トークンを使用して伝送されるユーザ ID は、トークンを作成するユーザによって決まります。
* トークンは 'Authorization'HTTP 要求ヘッダーに含める必要があります
* トークンは作成後に期限切れになることはありません。
* トークンは、 Astra の Web ユーザインターフェイスから取り消すことができます。


.関連情報
* link:../additional/revoke_token.html["API トークンを取り消します"]




== Astra API トークンを作成

Astra API トークンを作成する手順を次に示します。

Astra アカウントのクレデンシャルが必要です。

このタスクは、 Astra Web インターフェイスで API トークンを生成します。また、 API 呼び出しの際にも必要なアカウント ID を取得する必要があります。

.手順
. アカウントのクレデンシャルを使用して Astra にサインインします。
+
Astra Control Service の次のサイトにアクセスします。 https://astra.netapp.io/["https://astra.netapp.io"^]

. ページの右上にある図のアイコンをクリックし、 * API access * を選択します。
. ページで [API トークンの生成 ] をクリックし、ポップアップウィンドウで [API トークンの生成 ] をクリックします。
. アイコンをクリックしてトークン文字列をクリップボードにコピーし、エディタに保存します。
. 同じページにあるアカウント ID をコピーして保存します。


Curl またはプログラミング言語を使用して Astra Control REST API にアクセスする場合は、 API ベアラトークンを HTTP'Authorization' 要求ヘッダーに含める必要があります。
