---
sidebar: sidebar 
permalink: get-started/online_api_ref.html 
keywords: reference, api reference 
summary: HTTPメソッド、入力パラメータ、応答など、Astra Control REST API呼び出しの詳細にアクセスできます。このリファレンスは、 REST API を使用して自動化アプリケーションを開発する場合に役立ちます。 
---
= Astra APIのリファレンスドキュメントにアクセス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
HTTPメソッド、入力パラメータ、応答など、Astra Control REST API呼び出しの詳細にアクセスできます。このリファレンスは、 REST API を使用して自動化アプリケーションを開発する場合に役立ちます。

.作業を開始する前に
導入時にAstra Webユーザインターフェイスにサインインするには、クレデンシャルが必要です。リファレンスドキュメントにアクセスするための手順は、Astra ControlサービスとAstra Control Centerで同じです。URLだけが異なります。リファレンスドキュメントにアクセスして表示するためにAPIトークンは必要ありません。

.手順
. 次のアカウントクレデンシャルを使用してAstraにサインインします。
+
** Astra Controlサービス： link:https://astra.netapp.io["https://astra.netapp.io"^]
** Astra Control Center：インストール時に設定したローカル環境のURLを使用します


. ページの右上にある図のアイコンをクリックし、 * API access * を選択します。
. ページの上部で、 * API ドキュメント * の下に表示される URL をクリックします。


.結果
Swaggerページが新しいウィンドウまたはタブで表示されます。URLには、サインインしたアカウントのアカウントIDが含まれていることに注意してください。

.次の手順
必要に応じて、SwaggerページからAPI呼び出しを実行できます。を参照してください link:../get-started/online_api_call.html["問題Astra REST APIコール"] を参照してください。
