---
sidebar: sidebar 
permalink: get-started/prepare_to_use_workflows.html 
keywords: workflows, prepare workflows, use workflows 
summary: 実際の環境で使用する前に、 Astra ワークフローの構成と形式を理解しておく必要があります。 
---
= ワークフローを使用する準備をします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
実際の環境で使用する前に、 Astra ワークフローの構成と形式を理解しておく必要があります。



== はじめに

a_workflow_ は、特定の管理タスクまたは目標を達成するために必要な 1 つ以上のステップのシーケンスです。Astra Control ワークフローの各手順は、次のいずれかです。

* REST API 呼び出し（ cURL や JSON の例などの詳細を含む）
* 別の Astra ワークフローの呼び出し
* その他の関連タスク（必要な設計決定の実行など）


ワークフローには、各タスクを実行するために必要な主要な手順とパラメータが含まれています。自動化環境をカスタマイズするための出発点となります。


NOTE: ワークフローには1つのステップのみを含めることができます。これらのシングルステップワークフローは、複数のステップを含むワークフローとは少し異なります。たとえば、明示的なステップ名は削除されます。アクションまたは操作は、ワークフローのタイトルに基づいて明確にする必要があります。



== ワークフローのカテゴリ

導入モデルに応じて、幅広い種類の Astra ワークフローが用意されています。Astra Control Center を使用している場合は、インフラワークフローから始めて、管理ワークフローに進みます。Astra Control Service を使用すると、通常は管理ワークフローに直接移動できます。


NOTE: ワークフローのcURLのサンプルでは、Astra Control ServiceのURLを使用します。オンプレミスの Astra Control Center を使用している場合は、環境に応じて URL を変更する必要があります。



=== インフラワークフロー

これらのワークフローは、クレデンシャル、バケット、ストレージバックエンドなどの Astra インフラを処理します。Astra Control Center で必要ですが、ほとんどの場合は Astra Control Service でも使用できます。このワークフローでは、マネージドクラスタの構築と保守に必要なタスクを中心に説明します。



=== 管理ワークフロー

これらのワークフローは、管理対象クラスタのセットアップ後に使用できます。管理ワークフローでは、アプリケーションの保護とサポート処理（アプリケーションのバックアップ、リストア、クローニングなど）に重点が置かれます。



== 共通の入力パラメータ

以下に記載する入力パラメータは、 REST API 呼び出しを示すために使用するすべての cURL サンプルに共通しています。


NOTE: これらの入力パラメータは汎用的に必要なため、個々のワークフローでは詳しく説明していません。特定のカールの例に追加の入力パラメータが使用される場合は、「 * その他の入力パラメータ * 」セクションで説明します。



=== パスパラメータ

すべての REST API 呼び出しで使用されるエンドポイントパスには、次のパラメータが含まれています。も参照してください link:../rest-core/url_format.html["URL 形式"] を参照してください。

アカウント ID:: これは、 API 処理を実行する Astra アカウントを識別する UUIDv4 値です。を参照してください link:../get-started/get_api_token.html["API トークンを取得します"] アカウント ID の検索の詳細については、を参照してください。




=== 要求ヘッダー

REST API 呼び出しに応じて、いくつかの要求ヘッダーを含める必要があります。

承認:: ワークフロー内のすべての API 呼び出しで、ユーザを識別するための API トークンが必要です。トークンは 'Authorization' 要求ヘッダーに含める必要がありますを参照してください link:../get-started/get_api_token.html["API トークンを取得します"] API トークンの生成の詳細については、を参照してください。
コンテンツタイプ:: 要求の本文に JSON が含まれている HTTP POST 要求と PUT 要求では、 Astra リソースに基づいてメディアタイプを宣言する必要があります。たとえば ' 管理対象アプリケーションのスナップショットを作成するときに 'Content-Type:application/stra-pappSnap+JSOb' というヘッダーを含めることができます
同意します:: アストラリソースに基づいて、応答で想定されるコンテンツの特定のメディアタイプを宣言できます。たとえば ' 管理対象アプリケーションのバックアップを一覧表示するときに 'Accept:application/Astra-pappBackup+JSOb' というヘッダーを含めることができますただし、簡単にするために、ワークフロー内のカールサンプルはすべてのメディアタイプに対応しています。




== トークンと識別子の表示

cURL の例で使用される API トークンおよびその他の ID 値は不透明で、認識不能な意味はありません。サンプルの読みやすさを向上させるために、実際のトークンと ID 値は使用されません。代わりに、小さい予約済みキーワードが使用されます。これには次のような利点があります。

* cURL と JSON のサンプルは、より明確でわかりやすくなっています。
* すべてのキーワードは角かっこと大文字で同じ形式を使用するため、挿入または抽出する場所とコンテンツをすばやく識別できます。
* 元のパラメータをコピーして実際の配置で使用することはできないため、値は失われません。


変数はBashシェル環境で使用するためにフォーマットされています。各変数はドル記号で始まり、必要に応じて二重引用符で囲みます。これにより、Bashに認識されるようになります。名前には常に大文字が使用されます。

次に、 curl の例で使用される一般的な予約済みキーワードの一部を示します。このリストはすべてを網羅しているわけではなく、必要に応じてその他のキーワードが使用されていその意味はコンテキストに基づいて明確になる必要があります。

[cols="25,15,60"]
|===
| キーワード | を入力します | 説明 


| $ACCOUNT_ID | パス | API 処理を実行するアカウントを識別する UUIDv4 値。 


| $API_TOKEN | ヘッダー | 発信者を識別および認可するベアラトークン。 


| $APP_ID | パス | API呼び出しのアプリケーションを識別するUUIDv4値。 
|===


== Bashでの例の使用

ワークフローカールの例を直接使用する場合は、変数に含まれる変数を環境に適した値に更新する必要があります。以下で説明するように、サンプルを手動で編集するか、Bashシェルに依存して置換を行うことができます。


NOTE: Bashを使用する利点の1つは、curlコマンドごとに1回ではなく、シェルセッションで変数値を一度だけ設定できることです。

.手順
. Linuxまたは同様のオペレーティングシステムで提供されているBashシェルを開きます。
. 実行するcurlサンプルに含まれる変数値を設定します。例：
+
`$API_TOKEN=SGgpXHeco6M8PLxzIlgbztA4k3_eX4UCa842hOXHBFA=`

. ワークフローページからcurlの例をコピーし、シェルターミナルに貼り付けます。
. ENTER*キーを押して、次のタスクを実行します。
+
.. 設定した変数値を置き換えます。
.. curlコマンドを実行します。



